import os
import sys
import django

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'vidyahub.settings')
django.setup()

from main.models import Grade, Subject, Chapter, MCQQuestion

g = Grade.objects.get(name='NEET')
s = Subject.objects.get(name='Biology', grade=g)

chapters_pyqs = {
    "Structural Organisation in Animals and Plants": [
        ("Tissue for conduction of water in plants is:", "Xylem", "Phloem", "Cambium", "Cork", "A", "Xylem conducts water"),
        ("Bone is a type of:", "Cartilage", "Connective tissue", "Muscle tissue", "Nervous tissue", "B", "Bone is connective tissue"),
        ("Epithelial tissue is of:", "One layer", "Multiple layers", "Both A and B", "None", "C", "Epithelial can be simple or stratified"),
        ("Neurons are found in:", "Brain", "Spinal cord", "Nerves", "All", "D", "Neurons throughout nervous system"),
        ("Muscle fibers contain:", "Actin", "Myosin", "Both A and B", "None", "C", "Muscle fibers have actin and myosin"),
        ("Blood is a:", "Tissue", "Organ", "System", "None", "A", "Blood is connective tissue"),
        ("Cartilage lacks:", "Blood vessels", "Nerves", "Both A and B", "None", "C", "Cartilage is avascular"),
        ("Adipose tissue stores:", "Protein", "Glycogen", "Fat", "Water", "C", "Adipose stores fat"),
        ("Areolar tissue is found:", "Below skin", "Around organs", "Both A and B", "None", "C", "Areolar is widespread"),
        ("Stratified epithelium is in:", "Skin", "Mouth", "Both A and B", "None", "C", "Stratified in skin and mouth"),
        ("Squamous epithelium lines:", "Blood vessels", "Alveoli", "Both A and B", "None", "C", "Squamous in vessels and alveoli"),
        ("Goblet cells secrete:", "Enzymes", "Mucus", "Hormones", "None", "B", "Goblet cells produce mucus"),
        ("Ciliated epithelium is in:", "Respiratory tract", "Fallopian tube", "Both A and B", "None", "C", "Ciliated in respiratory and oviduct"),
        ("Melanin is in:", "Melanocytes", "Keratinocytes", "Fibroblasts", "None", "A", "Melanin from melanocytes"),
        ("Collagen is in:", "Bone", "Cartilage", "Tendons", "All", "D", "Collagen in connective tissues"),
        ("Plasma cells secrete:", "Antibodies", "Antigens", "Hormones", "None", "A", "Plasma cells produce antibodies"),
        ("Mast cells release:", "Histamine", "Heparin", "Both A and B", "None", "C", "Mast cells release histamine and heparin"),
        ("Macrophages are from:", "Monocytes", "Lymphocytes", "Neutrophils", "None", "A", "Macrophages from monocytes"),
        ("Fibroblasts form:", "Collagen", "Elastin", "Both A and B", "None", "C", "Fibroblasts produce collagen and elastin"),
        ("Chondrocytes are in:", "Bone", "Cartilage", "Tendon", "None", "B", "Chondrocytes in cartilage"),
        ("Osteocytes are in:", "Bone", "Cartilage", "Marrow", "None", "A", "Osteocytes in bone"),
        ("Hyaline cartilage is in:", "Nose", "Ear", "Epiglottis", "None", "A", "Hyaline in nose"),
        ("Elastic cartilage is in:", "Ear", "Epiglottis", "None", "None", "A", "Elastic in ear"),
        ("Fibrocartilage is in:", "Intervertebral discs", "Pubic symphysis", "Both A and B", "None", "C", "Fibrocartilage in discs and symphysis"),
        ("Cardiac muscle is:", "Striated", "Involuntary", "Both A and B", "None", "C", "Cardiac striated involuntary"),
        ("Smooth muscle is in:", "Intestine", "Blood vessels", "Both A and B", "None", "C", "Smooth in gut and vessels"),
        ("Neuroglial cells are:", "Neurons", "Supporting cells", "Gland cells", "None", "B", "Neuroglial are supporting"),
        ("Schwann cells form:", "Myelin", "Synapse", "Receptor", "None", "A", "Schwann cells produce myelin"),
        ("Gap junctions are in:", "Heart", "Intestine", "Skin", "None", "A", "Gap junctions in cardiac muscle"),
        ("Tight junctions are in:", "Blood-brain barrier", "Intestine", "Both A and B", "None", "C", "Tight junctions in barriers"),
        ("Basement membrane has:", "Collagen", "Laminin", "Both A and B", "None", "C", "Basement membrane collagen and laminin"),
    ],
    "Cell Structure and Function": [
        ("Who discovered cell?", "Robert Hooke", "Schleiden", "Schwann", "Virchow", "A", "Hooke discovered cell in 1665"),
        ("Cell theory was given by:", "Hooke", "Schleiden and Schwann", "Virchow", "Rudolf Virchow", "B", "Schleiden and Schwann formulated cell theory"),
        ("Nucleus was discovered by:", "Robert Brown", "Schleiden", "Schwann", "Dujardin", "A", "Robert Brown discovered nucleus"),
        ("DNA is in:", "Nucleus", "Mitochondria", "Both A and B", "Cytoplasm", "C", "DNA in nucleus and mitochondria"),
        ("Ribosomes are made of:", "RNA and protein", "DNA and protein", "Lipids", "Carbohydrates", "A", "Ribosomes RNA-protein complexes"),
        ("Powerhouse of cell is:", "Nucleus", "Mitochondria", "Ribosome", "Golgi body", "B", "Mitochondria produce ATP"),
        ("Cell membrane is:", "Phospholipid bilayer", "Protein bilayer", "Carbohydrate bilayer", "None", "A", "Cell membrane phospholipid bilayer"),
        ("Endoplasmic reticulum is absent in:", "Prokaryotes", "Eukaryotes", "Plant cells", "Animal cells", "A", "ER absent in prokaryotes"),
        ("Lysosomes contain:", "DNA", "RNA", "Hydrolytic enzymes", "ATP", "C", "Lysosomes have hydrolytic enzymes"),
        ("Golgi apparatus is for:", "Protein synthesis", "Protein packaging", "DNA replication", "Energy production", "B", "Golgi packages proteins"),
        ("Centrosome helps in:", "Respiration", "Cell division", "Protein synthesis", "Transport", "B", "Centrosome forms spindle"),
        ("Plasmolysis occurs in:", "Isotonic", "Hypertonic", "Hypotonic", "None", "B", "Plasmolysis in hypertonic solution"),
        ("RBCs lack:", "Nucleus", "Mitochondria", "Cell membrane", "Hemoglobin", "B", "Mature RBCs lack mitochondria"),
        ("Mitochondria are inherited from:", "Father", "Mother", "Both", "Neither", "B", "Mitochondrial DNA from mother"),
        ("Cell wall is absent in:", "Plant cells", "Animal cells", "Bacteria", "Fungi", "B", "Animal cells lack cell wall"),
        ("Unit of inheritance is:", "DNA", "Gene", "Chromosome", "Nucleus", "B", "Gene is unit of inheritance"),
        ("Nuclear envelope is absent in:", "Plant cells", "Animal cells", "Prokaryotes", "Fungi", "C", "Prokaryotes lack nuclear envelope"),
        ("Ribosomes were discovered by:", "Porter", "Robertson", "Kollicer", "Robert Hooke", "C", "Kollicer discovered ribosomes"),
        ("Cristae are in:", "Nucleus", "Mitochondria", "Ribosome", "Golgi", "B", "Cristae in mitochondria"),
        ("Which organelle is semi-autonomous?", "Ribosome", "Mitochondria", "Lysosome", "Peroxisome", "B", "Mitochondria semi-autonomous"),
        ("Cell ingestion is:", "Exocytosis", "Endocytosis", "Pinocytosis", "Phagocytosis", "B", "Endocytosis cell ingestion"),
        ("Fluid mosaic model was given by:", "Singer", "Nicolson", "Both A and B", "Robertson", "C", "Singer and Nicolson proposed model"),
        ("Nucleolus is not surrounded by:", "Membrane", "DNA", "RNA", "Proteins", "A", "Nucleolus has no membrane"),
        ("Vacuoles are prominent in:", "Animal cells", "Plant cells", "Bacterial cells", "None", "B", "Plant cells have large vacuoles"),
        ("Chromatid becomes chromosome during:", "Interphase", "Prophase", "Anaphase", "Telophase", "C", "Chromatids separate in anaphase"),
        ("Cell organelle not membrane-bound:", "Ribosome", "Lysosome", "Mitochondria", "Golgi", "A", "Ribosome not membrane-bound"),
        ("Middle lamella is of:", "Protein", "Pectin", "Cellulose", "Lignin", "B", "Middle lamella pectin"),
        ("Plasmodesmata connect:", "Two cells", "Two nuclei", "Cytoplasm of adjacent cells", "All", "C", "Connect cytoplasm"),
        ("Cell communication via:", "Tankers", "Gap junctions", "Desmosomes", "Hemidesmosomes", "B", "Gap junctions for communication"),
        ("Cell drinking is:", "Phagocytosis", "Pinocytosis", "Exocytosis", "None", "B", "Pinocytosis is cell drinking"),
        ("Mitochondrial DNA is:", "Circular", "Linear", "Both", "None", "A", "Mitochondrial DNA is circular"),
    ],
    "Plant Physiology": [
        ("Photosynthesis occurs in:", "Chloroplast", "Mitochondria", "Ribosome", "None", "A", "Photosynthesis in chloroplast"),
        ("Light reactions occur in:", "Stroma", "Thylakoid", "Granum", "None", "B", "Light reactions in thylakoid"),
        ("Dark reactions occur in:", "Stroma", "Thylakoid", "Membrane", "None", "A", "Calvin cycle in stroma"),
        ("Chlorophyll is in:", "Thylakoid membrane", "Stroma", "Envelope", "None", "A", "Chlorophyll in thylakoid"),
        ("Photolysis of water occurs in:", "PS I", "PS II", "Both", "None", "B", "Photolysis in PSII"),
        ("O2 comes from:", "CO2", "Water", "Mineral", "Air", "B", "Oxygen from water"),
        ("Primary CO2 acceptor is:", "RUBP", "RuBP", "Malic acid", "PEP", "B", "RuBP is CO2 acceptor"),
        ("C3 plants are:", "Wheat", "Rice", "Both A and B", "None", "C", "Wheat and rice are C3"),
        ("C4 plants have:", "One cell", "Two cells", "No cells", "Three cells", "B", "Kranz anatomy"),
        ("PEP carboxylase is in:", "Mesophyll", "Bundle sheath", "Both", "None", "A", "PEP in mesophyll"),
        ("CAM plants open stomata:", "Day", "Night", "Both", "None", "B", "CAM at night"),
        ("ATP synthase is in:", "Stroma", "Thylakoid membrane", "Grana", "None", "B", "ATP synthase in thylakoid"),
        ("Chlorophyll a absorbs:", "Red and blue", "Green", "Yellow", "All", "A", "Chlorophyll a red and blue"),
        ("Photorespiration in:", "C4 plants", "C3 plants", "CAM plants", "None", "B", "Photorespiration in C3"),
        ("Warburg effect is:", "Low O2 inhibits photosynthesis", "High O2 inhibits", "CO2 inhibits", "None", "B", "High O2 inhibits photosynthesis"),
        ("Calvin cycle in:", "Stroma", "Thylakoid", "Cytoplasm", "None", "A", "Calvin in stroma"),
        ("PGAL is product of:", "Reduction", "Regeneration", "Carbon fixation", "All", "A", "PGAL in reduction phase"),
        ("Rubisco is:", "Protease", "Carboxylase", "Oxidase", "None", "B", "Rubisco is carboxylase"),
        ("Non-cyclic photophosphorylation produces:", "ATP", "NADPH", "O2", "All", "D", "Produces ATP, NADPH, O2"),
        ("Cyclic produces:", "ATP", "NADPH", "O2", "All", "A", "Only ATP"),
        ("Transpiration is:", "Beneficial", "Harmful", "Both", "None", "C", "Both helpful and harmful"),
        ("Stomata open by:", "K+ influx", "K+ efflux", "Cl- efflux", "None", "A", "K+ influx opens stomata"),
        ("Abscisic acid causes:", "Stomatal opening", "Stomatal closure", "Growth", "None", "B", "ABA closes stomata"),
        ("Guttation is due to:", "Transpiration", "Root pressure", "Capillarity", "None", "B", "Root pressure causes guttation"),
        ("Cohesion theory by:", "Dixon", "Jensen", "Crafts", "Ghosh", "A", "Dixon and Joly proposed"),
        ("Ascent of sap is due to:", "Root pressure", "Transpiration pull", "Capillarity", "All", "D", "Multiple forces"),
        ("Mycorrhiza helps in:", "Water absorption", "Mineral absorption", "Both A and B", "None", "C", "Both water and minerals"),
        ("Nitrogen fixation by:", "Rhizobium", "Nostoc", "Both A and B", "None", "C", "Both bacteria fix nitrogen"),
        ("Leghemoglobin protects:", "Nitrogenase", "Nod factor", "Both", "None", "A", "Leghemoglobin protects nitrogenase"),
        ("Carnivorous plants grow in:", "Nitrogen-rich soil", "Nitrogen-deficient soil", "Water-rich soil", "None", "B", "N-deficient soil"),
    ],
    "Human Physiology": [
        ("Human digestive system includes:", "Mouth", "Stomach", "Intestine", "All", "D", "Complete digestive tract"),
        ("Maximum digestion in:", "Stomach", "Small intestine", "Large intestine", "Buccal cavity", "B", "Small intestine"),
        ("Bile emulsifies:", "Proteins", "Fats", "Carbohydrates", "All", "B", "Bile emulsifies fats"),
        ("Pepsin digests:", "Proteins", "Fats", "Carbohydrates", "All", "A", "Pepsin digests proteins"),
        ("Trypsin activated by:", "HCl", "Enterokinase", "Bile", "Lipase", "B", "Enterokinase activates trypsin"),
        ("Intestinal enzymes are:", "Maltase", "Sucrase", "Lactase", "All", "D", "All disaccharidases"),
        ("Maximum absorption in:", "Duodenum", "Jejunum", "Ileum", "None", "B", "Jejunum most absorption"),
        ("Villi are in:", "Stomach", "Small intestine", "Large intestine", "None", "B", "Villi in small intestine"),
        ("Chylomicrons enter:", "Blood", "Lymph", "Both", "None", "B", "Chylomicrons in lymph"),
        ("Respiration is:", "External", "Internal", "Cellular", "All", "D", "All three types"),
        ("Lungs contain:", "Alveoli", "Bronchi", "Bronchioles", "All", "D", "All components"),
        ("Surfactant is from:", "Type I pneumocytes", "Type II pneumocytes", "Macrophages", "None", "B", "Type II cells secrete surfactant"),
        ("Vital capacity is:", "TV + IRV + ERV", "TV + IRV", "IRV + ERV", "None", "A", "VC = TV + IRV + ERV"),
        ("O2 is carried by:", "Hemoglobin", "Myoglobin", "Both A and B", "None", "C", "Both Hb and Mb carry O2"),
        ("CO2 is carried as:", "Bicarbonate", "Carbaminohemoglobin", "Dissolved", "All", "D", "All three forms"),
        ("Blood is:", "Tissue", "Organ", "System", "None", "A", "Blood is connective tissue"),
        ("RBC count males:", "4.5-5.5 million", "3.5-4.5 million", "5.5-6.5 million", "None", "A", "4.5-5.5 million"),
        ("WBC count:", "6000-10000", "4000-11000", "5000-9000", "None", "B", "4000-11000 per cmm"),
        ("Platelets:", "1.5-3.5 lakh", "1-3 lakh", "2-4 lakh", "None", "A", "1.5-3.5 lakh"),
        ("Universal donor:", "O-", "O+", "AB+", "AB-", "A", "O negative"),
        ("Universal recipient:", "O-", "O+", "AB+", "AB-", "C", "AB positive"),
        ("Heart is:", "Endocrine", "Exocrine", "Both", "None", "C", "Heart has both functions"),
        ("SA node is in:", "Right atrium", "Left atrium", "Ventricle", "None", "A", "SA node in right atrium"),
        ("Heart sound is:", "Lub", "Dub", "Both", "None", "C", "First and second sounds"),
        ("Systolic pressure:", "120 mmHg", "110 mmHg", "130 mmHg", "100 mmHg", "A", "120 mmHg"),
        ("Diastolic pressure:", "80 mmHg", "70 mmHg", "90 mmHg", "60 mmHg", "A", "80 mmHg"),
        ("Nephron is unit of:", "Liver", "Kidney", "Heart", "Lungs", "B", "Nephron in kidney"),
        ("GFR is:", "125 ml/min", "180 ml/min", "100 ml/min", "None", "A", "125 ml/min"),
        ("ADH acts on:", "Proximal tubule", "Loop of Henle", "Distal tubule", "Collecting duct", "D", "ADH on collecting duct"),
        ("Kidney stones are:", "Calcium oxalate", "Uric acid", "Cystine", "All", "D", "Various compositions"),
    ],
    "Reproduction": [
        ("Sexual reproduction involves:", "Gametes", "Spores", "Budding", "Fragmentation", "A", "Gamete fusion"),
        ("Male gamete is:", "Sperm", "Ovum", "Zygote", "None", "A", "Sperm is male gamete"),
        ("Female gamete is:", "Sperm", "Ovum", "Zygote", "None", "B", "Ovum is female gamete"),
        ("Fertilization is:", "Fusion of gametes", "Cell division", "Growth", "None", "A", "Gamete fusion"),
        ("Zygote is:", "Haploid", "Diploid", "Triploid", "Polyploid", "B", "Zygote is diploid"),
        ("Embryo develops from:", "Zygote", "Gametes", "Spores", "None", "A", "Embryo from zygote"),
        ("Pregnancy test detects:", "hCG", "FSH", "LH", "Estrogen", "A", "hCG in pregnancy test"),
        ("Placenta is:", "Structural", "Nutritional", "Endocrine", "All", "D", "Placenta has multiple functions"),
        ("Human gestation period is:", "270 days", "280 days", "290 days", "260 days", "B", "About 280 days"),
        ("Parturition is triggered by:", "Oxytocin", "Prolactin", "Estrogen", "None", "A", "Oxytocin causes labor"),
        ("Spermatogenesis occurs in:", "Testes", "Epididymis", "Vas deferens", "None", "A", "Spermatogenesis in testes"),
        ("Oogenesis occurs in:", "Ovary", "Fallopian tube", "Uterus", "None", "A", "Oogenesis in ovary"),
        ("Menstrual cycle is:", "28 days", "30 days", "35 days", "25 days", "A", "28 days average"),
        ("Ovulation occurs on:", "Day 14", "Day 10", "Day 20", "None", "A", "Mid-cycle at day 14"),
        ("Corpus luteum secretes:", "Progesterone", "Estrogen", "Both A and B", "None", "C", "Progesterone and estrogen"),
        ("IVF is:", "In vivo", "In vitro", "Both", "None", "B", "Fertilization in vitro"),
        ("MTP is:", "Medical termination", "Menstrual treatment", "Both", "None", "A", "Medical termination of pregnancy"),
        ("STD caused by bacteria:", "Syphilis", "Gonorrhea", "Both A and B", "None", "C", "Both are bacterial STDs"),
        ("HIV attacks:", "RBCs", "WBCs", "Platelets", "None", "B", "HIV attacks CD4 cells"),
        ("AIDS is transmitted by:", "Blood", "Sexual contact", "Both A and B", "None", "C", "Both blood and sexual"),
        ("Contraceptive pills contain:", "Estrogen", "Progesterone", "Both A and B", "None", "C", "Combined pills"),
        ("Copper-T is:", "Barrier", "Intrauterine device", "Hormonal", "None", "B", "IUD"),
        ("Vasectomy is:", "Male sterilization", "Female sterilization", "Both", "None", "A", "Male contraception"),
        ("Tubectomy is:", "Male sterilization", "Female sterilization", "Both", "None", "B", "Female contraception"),
        ("Amniocentesis detects:", "Genetic disorders", "Hormonal disorders", "Both", "None", "A", "Genetic abnormalities"),
        ("Ultrasound is:", "Radiological", "Sound waves", "Magnetic", "None", "B", "Uses sound waves"),
        ("GIFT is:", "Gamete transfer", "Embryo transfer", "Both", "None", "A", "Gamete intrafallopian transfer"),
        ("ICSI is:", "IVF variant", "Gift variant", "Both", "None", "A", "Intracytoplasmic sperm injection"),
        ("Assisted reproductive technology includes:", "IVF", "GIFT", "ZIFT", "All", "D", "All ART techniques"),
        ("Infertility is due to:", "Male factors", "Female factors", "Both", "None", "C", "Can be from either or both"),
    ],
    "Genetics and Evolution": [
        ("Heredity is study of:", "Variation", "Inheritance", "Both", "None", "B", "Inheritance of traits"),
        ("Mendel is father of:", "Genetics", "Evolution", "Ecology", "None", "A", "Mendelian genetics"),
        ("Gene is unit of:", "Heredity", "Mutation", "Variation", "None", "A", "Gene is hereditary unit"),
        ("DNA is genetic material in:", "Prokaryotes", "Eukaryotes", "Viruses", "All", "D", "DNA in all organisms"),
        ("RNA is genetic material in:", "Prokaryotes", "Eukaryotes", "Some viruses", "None", "C", "RNA viruses"),
        ("DNA structure is:", "Double helix", "Single helix", "Triple helix", "None", "A", "Watson and Crick model"),
        ("Base pairing is:", "Complementary", "Random", "Both", "None", "A", "A-T, G-C pairing"),
        ("Replication is:", "Semi-conservative", "Conservative", "Dispersive", "None", "A", "Semi-conservative replication"),
        ("Transcription is:", "DNA to RNA", "RNA to DNA", "Protein to RNA", "None", "A", "DNA to RNA"),
        ("Translation is:", "RNA to Protein", "DNA to Protein", "Protein to RNA", "None", "A", "Protein synthesis"),
        ("Codons are in:", "DNA", "RNA", "Protein", "None", "B", "Codons in mRNA"),
        ("Start codon is:", "AUG", "UAA", "UAG", "UGA", "A", "AUG codes for methionine"),
        ("Stop codons are:", "UAA, UAG, UGA", "AUG", "GUG", "None", "A", "Three stop codons"),
        ("One codon codes for:", "One amino acid", "Multiple amino acids", "No amino acid", "None", "A", "One codon one amino acid"),
        ("Genetic code is:", "Universal", "Specific", "Both", "None", "A", "Almost universal"),
        ("Mutation is change in:", "Genotype", "Phenotype", "Both", "None", "C", "Can affect genotype and phenotype"),
        ("Gene therapy is:", "Treating genetic disorders", "Creating disorders", "Both", "None", "A", "Treating genetic diseases"),
        ("Human genome project mapped:", "DNA sequence", "Gene locations", "Both", "None", "C", "Complete human genome"),
        ("Evolution is:", "Descent with modification", "突 Sudden change", "Both", "None", "A", "Darwin's theory"),
        ("Natural selection is:", "Survival of fittest", "Random", "Both", "None", "A", "Darwin's mechanism"),
        ("Adaptation is:", "Favorable trait", "Unfavorable trait", "Neutral", "None", "A", "Favorable for survival"),
        ("Speciation is formation of:", "New species", "New genera", "Both", "None", "A", "New species"),
        ("Natural selection acts on:", "Phenotype", "Genotype", "Both", "None", "C", "Acts on variation"),
        ("Founder effect is:", "Small population", "Large population", "Both", "None", "A", "Genetic drift in small population"),
        ("Hardy-Weinberg equilibrium is for:", "Non-evolving population", "Evolving population", "Both", "None", "A", "No evolution"),
        ("Heterozygote has:", "Dominant and recessive alleles", "Two dominant", "Two recessive", "None", "A", "One allele of each type"),
        ("Incomplete dominance shows:", "Blended traits", "Distinct traits", "No traits", "None", "A", "Intermediate phenotype"),
        ("Codominance shows:", "Both traits expressed", "Blended traits", "No traits", "None", "A", "Both alleles expressed"),
        ("Polygenic inheritance is for:", "Quantitative traits", "Qualitative traits", "Both", "None", "A", "Multiple genes affect trait"),
        ("Linked genes are on:", "Same chromosome", "Different chromosomes", "Both", "None", "A", "On same chromosome"),
    ],
    "Biology and Human Welfare": [
        ("Animal husbandry includes:", "Poultry", "Dairy", "Both", "None", "C", "Animal farming"),
        ("Poultry farming is for:", "Eggs", "Meat", "Both", "None", "C", "Eggs and meat production"),
        ("Dairy farming is for:", "Milk", "Milk products", "Both", "None", "C", "Milk and dairy products"),
        ("Inland fishing is in:", "Lakes", "Rivers", "Both", "None", "C", "Freshwater fishing"),
        ("Marine fishing is in:", "Sea", "Ocean", "Both", "None", "C", "Saltwater fishing"),
        ("Blue revolution is about:", "Fish production", "Crop production", "Milk production", "None", "A", "Aquaculture development"),
        ("Apiculture is:", "Bee keeping", "Silkworm rearing", "Both", "None", "A", "Honey bee farming"),
        ("Sericulture is:", "Bee keeping", "Silkworm rearing", "Both", "None", "B", "Silkworm farming"),
        ("Morus alba is:", "Mulberry", "S印度", "Both", "None", "A", "Food plant for silkworm"),
        ("Mulberry is for:", "Silkworm", "Apiculture", "Both", "None", "A", "Silkworm food"),
        ("Plant breeding is:", "Crop improvement", "Animal improvement", "Both", "None", "A", "Genetic crop improvement"),
        ("Hybridization is:", "Cross between varieties", "Within variety", "Both", "None", "A", "Cross breeding"),
        ("Mutation breeding uses:", "Radiation", "Chemicals", "Both", "None", "C", "Induced mutations"),
        ("Tissue culture is:", "In vitro propagation", "In vivo propagation", "Both", "None", "A", "Plant tissue culture"),
        ("Golden rice has:", "Vitamin A", "Vitamin C", "Vitamin B", "None", "A", "Beta-carotene"),
        ("Biofortification is:", "Enriching nutrients", "Adding toxins", "Both", "None", "A", "Nutrient enrichment"),
        ("NEET important for:", "Human health", "Animal health", "Plant health", "All", "D", "All biology fields"),
        ("Pathogenic bacteria cause:", "Diseases", "Benefits", "Both", "None", "C", "Can cause diseases"),
        ("Antibiotics target:", "Bacteria", "Viruses", "Fungi", "None", "A", "Antibiotics for bacteria"),
        ("Vaccines provide:", "Active immunity", "Passive immunity", "Both", "None", "A", "Active immunity"),
        ("Antibodies are:", "Proteins", "Carbohydrates", "Lipids", "None", "A", "Immunoglobulins are proteins"),
        ("Antigens are:", "Foreign substances", "Self substances", "Both", "None", "A", "Foreign substances"),
        ("Immune system has:", "Specific response", "Non-specific response", "Both", "None", "C", "Both innate and adaptive"),
        ("Lymphocytes are:", "WBCs", "RBCs", "Platelets", "None", "A", "White blood cells"),
        ("Macrophages are:", "Phagocytes", "Secretory cells", "Both", "None", "A", "Phagocytic cells"),
        ("Allergy is:", "Hypersensitivity", "Normal response", "No response", "None", "A", "Excessive immune response"),
        ("Autoimmune disease is when:", "Body attacks itself", "Attacks pathogens", "No response", "None", "A", "Self-attack"),
        ("Immunodeficiency is:", "Weak immune system", "Strong immune system", "None", "None", "A", "Compromised immunity"),
        ("Cancer is:", "Uncontrolled division", "Controlled division", "No division", "None", "A", "Abnormal cell division"),
        ("Tumors are:", "Benign", "Malignant", "Both", "None", "C", "Can be benign or malignant"),
    ],
    "Biotechnology and Its Applications": [
        ("Biotechnology uses:", "Living organisms", "Biological systems", "Both", "None", "C", "Uses living systems"),
        ("Genetic engineering is:", "Gene manipulation", "Cell manipulation", "Both", "None", "A", "Direct gene manipulation"),
        ("Recombinant DNA is:", "Combined DNA", "Native DNA", "Both", "None", "A", "DNA from different sources"),
        ("Vectors are for:", "Gene transfer", "Gene storage", "Both", "None", "A", "Carrying foreign DNA"),
        ("Plasmid is:", "Extra-chromosomal DNA", "Chromosomal DNA", "Both", "None", "A", "Circular DNA in bacteria"),
        ("Restriction enzymes cut:", "DNA", "RNA", "Protein", "None", "A", "DNA at specific sites"),
        ("Ligase joins:", "DNA strands", "RNA strands", "Both", "None", "C", "DNA and RNA"),
        ("PCR is:", "Polymerase chain reaction", "Protein chain reaction", "Both", "None", "A", "DNA amplification"),
        ("DNA polymerase in PCR:", "Taq polymerase", "Normal polymerase", "Both", "None", "A", "Heat-stable enzyme"),
        ("Gel electrophoresis separates:", "DNA", "RNA", "Protein", "All", "D", "Nucleic acids and proteins"),
        ("Blotting techniques are:", "DNA", "RNA", "Protein", "All", "D", "Southern, Northern, Western"),
        ("DNA finger printing is for:", "Identification", "Gene therapy", "Both", "None", "A", "Forensic identification"),
        ("Gene therapy treats:", "Genetic disorders", "Infectious diseases", "Both", "None", "A", "Correcting genetic defects"),
        ("Transgenic organisms have:", "Foreign gene", "Native gene", "Both", "None", "A", "Genetically modified"),
        ("Bt cotton has:", "Insect resistance", "Herbicide tolerance", "Both", "None", "C", "Multiple traits"),
        ("Gene bank stores:", "Genes", "Organisms", "DNA", "All", "D", "Genetic material"),
        ("RNAi is for:", "Gene silencing", "Gene amplification", "Both", "None", "A", "Knockdown gene expression"),
        ("Bioreactor is for:", "Large scale production", "Small scale", "Both", "None", "A", "Industrial production"),
        ("Fermentation uses:", "Microorganisms", "Enzymes", "Both", "None", "C", "Biological processes"),
        ("Penicillin is from:", "Fungi", "Bacteria", "Both", "None", "A", "From Penicillium"),
        ("Insulin is from:", "Human gene", "Pig", "Cow", "None", "A", "Recombinant DNA technology"),
        ("Growth hormone is from:", "Human gene", "Animal", "Both", "None", "A", "Recombinant GH"),
        ("Vaccines now include:", "Recombinant", "Killed pathogen", "Toxoid", "All", "D", "Various types"),
        ("DNA vaccine uses:", "Gene", "Killed virus", "Attenuated virus", "None", "A", "DNA itself as vaccine"),
        ("Stem cells are:", "Undifferentiated", "Differentiated", "Both", "None", "A", "Can become any cell"),
        ("ESC are from:", "Embryo", "Adult", "Both", "None", "A", "Embryonic stem cells"),
        ("Cloning is:", "Creating identical copy", "Different copy", "Both", "None", "A", "Genetic copy"),
        ("Dolly sheep was:", "Clone", "Transgenic", "Both", "None", "A", "First mammalian clone"),
        ("Bioinformatics is:", "Biological data analysis", "Data storage", "Both", "None", "A", "Computational biology"),
        ("Genome projects generate:", "Sequence data", "Map data", "Both", "None", "C", "Massive data"),
    ],
    "Ecology and Environment": [
        ("Ecology is study of:", "Organisms and environment", "Organisms only", "Environment only", "None", "A", "Interactions"),
        ("Ecosystem includes:", "Biotic factors", "Abiotic factors", "Both", "None", "C", "All components"),
        ("Producers are:", "Autotrophs", "Heterotrophs", "Both", "None", "A", "Make their own food"),
        ("Consumers are:", "Autotrophs", "Heterotrophs", "Both", "None", "B", "Depend on others"),
        ("Decomposers are:", "Fungi", "Bacteria", "Both", "None", "C", "Break down dead matter"),
        ("Food chain shows:", "Energy flow", "Matter flow", "Both", "None", "C", "Energy and matter"),
        ("Food web is:", "Interconnected food chains", "Single chain", "Both", "None", "A", "Complex feeding"),
        ("Primary productivity is:", "Rate of biomass production", "Amount of biomass", "Both", "None", "A", "Rate of production"),
        ("Greenhouse gases are:", "CO2", "CH4", "Both A and B", "None", "C", "Carbon dioxide and methane"),
        ("Global warming is due to:", "Greenhouse gases", "Ozone depletion", "Both", "None", "A", "Greenhouse effect"),
        ("Ozone layer is in:", "Troposphere", "Stratosphere", "Mesosphere", "None", "B", "Stratospheric ozone"),
        ("Acid rain is due to:", "SO2", "NO2", "Both A and B", "None", "C", "Sulfur and nitrogen oxides"),
        ("Eutrophication is:", "Nutrient enrichment", "Nutrient depletion", "Both", "None", "A", "Excess nutrients"),
        ("Biomagnification is:", " toxin accumulation", "Nutrient accumulation", "Both", "None", "A", "Toxin increase in food chain"),
        ("Endangered species need:", "Protection", "Conservation", "Both", "None", "C", "Protection and conservation"),
        ("Wildlife protection act is:", "1972", "1980", "1986", "1972", "A", "Indian Wildlife Protection Act"),
        ("Biodiversity is:", "Species diversity", "Genetic diversity", "Both", "None", "C", "Variety of life"),
        ("Hotspots are:", "High biodiversity areas", "Low biodiversity", "Both", "None", "A", "Ecologically rich areas"),
        ("Niche is:", "Role of species", "Place of species", "Both", "None", "C", "Role and place"),
        ("Predator-prey relationship is:", "Controls population", "Increases population", "Both", "None", "A", "Population control"),
        ("Symbiosis is:", "Close relationship", "No relationship", "Both", "None", "A", "Living together"),
        (" commensalism one benefits:", "Both", "One benefits only", "None", "B", "One benefits no effect on other"),
        ("Parasitism is:", "One benefits", "Both benefit", "None", "A", "One benefits at other's cost"),
        ("Mutualism is:", "Both benefit", "One benefits", "None", "A", "Both benefit"),
        ("Nitrogen cycle has:", "N2 fixation", "Denitrification", "Both", "None", "C", "Fixation and release"),
        ("Carbon cycle includes:", "Photosynthesis", "Respiration", "Both", "None", "C", "Carbon flow"),
        ("Water cycle is:", "Evaporation", "Precipitation", "Both", "None", "C", "Water movement"),
        ("Ecological pyramid is:", "Energy", "Number", "Biomass", "All", "D", "Various pyramids"),
        ("10% rule is:", "Energy transfer", "Biomass transfer", "Both", "None", "A", "10% energy transfer"),
        ("Succession is:", "Community change", "No change", "Both", "None", "A", "Gradual change"),
    ],
}

total = 0
for chapter_name, pyqs in chapters_pyqs.items():
    try:
        c = Chapter.objects.get(subject=s, name=chapter_name)
        MCQQuestion.objects.filter(chapter=c).delete()
        for order, q in enumerate(pyqs):
            MCQQuestion.objects.create(
                chapter=c,
                question_text=q[0],
                option_a=q[1],
                option_b=q[2],
                option_c=q[3],
                option_d=q[4],
                correct_option=q[5],
                explanation=q[6],
                order=order
            )
        print(f"Added {len(pyqs)} PYQs to {chapter_name}")
        total += len(pyqs)
    except Chapter.DoesNotExist:
        print(f"Chapter {chapter_name} not found - skipping")
    except Exception as e:
        print(f"Error with {chapter_name}: {e}")

print(f"\nTotal added: {total} PYQs to NEET Biology")