services:
  - type: web
    name: vidyahub
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput && python scripts/seeding/seed_master.py
    startCommand: gunicorn run_combined:combined_app --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.10"
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: AI_SIMULATION_MODE
        value: "False"
      - key: PRODUCTION
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: vidyahub-db
          property: connectionString
