# Generated by Django 5.2.6 on 2026-04-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_last_quiz_date_profile_level_profile_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_exam',
            field=models.CharField(choices=[('none', 'None'), ('jee', 'JEE (Engineering)'), ('neet', 'NEET (Medical)')], default='none', help_text='For JEE/NEET students', max_length=20),
        ),
    ]
