# Generated by Django 5.2.6 on 2026-04-23 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_target_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('category', models.CharField(choices=[('streak', 'Streak'), ('quiz', 'Quiz'), ('game', 'Game'), ('social', 'Social'), ('special', 'Special')], max_length=20)),
                ('xp_reward', models.IntegerField(default=50)),
                ('requirement_type', models.CharField(max_length=50)),
                ('requirement_value', models.IntegerField()),
                ('rarity', models.CharField(default='common', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(unique=True)),
                ('xp_reward', models.IntegerField(default=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='perfect_scores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_quizzes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_exam',
            field=models.CharField(choices=[('none', 'None'), ('jee', 'JEE (Engineering)'), ('neet', 'NEET (Medical)'), ('nda', 'NDA (Defence)')], default='none', help_text='For JEE/NEET students', max_length=20),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
