# Generated by Django 5.2.6 on 2026-04-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_avatar_userchallenge_friend_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='battle_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='battles_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='battles_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='highest_battle_streak',
            field=models.IntegerField(default=0),
        ),
    ]
