# Generated by Django 5.2.6 on 2026-04-25 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_battle_streak_profile_battles_played_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNoteUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='teacher_notes/')),
                ('game_levels_json', models.JSONField(blank=True, help_text='5 Game Levels summary', null=True)),
                ('blindspots_json', models.JSONField(blank=True, help_text='Student difficult spots', null=True)),
                ('quiz_questions_json', models.JSONField(blank=True, help_text='10 Generated Quiz Questions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_uploads', to='main.chapter')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
