"""
Django settings for vidyahub project.
# Reloaded for Cerebras configuration

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-@88&mrlei00926axdi7mtbhg=*-2ghgmo1z%*2x+e7*=dlga!l')

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False if PRODUCTION is set, else True for local dev
_is_prod = os.getenv('PRODUCTION', 'False').lower() == 'true'
DEBUG = os.getenv('DEBUG', str(not _is_prod)).lower() == 'true'

ALLOWED_HOSTS = ['*']
if os.getenv('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(os.getenv('RENDER_EXTERNAL_HOSTNAME'))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vidyahub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vidyahub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/topics/db/sqlite3/

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'check_same_thread': False,
            'timeout': 30,
        },
    }
}

# Override with PostgreSQL if DATABASE_URL is set (Render deployment)
import dj_database_url

_raw_db_url = os.getenv("DATABASE_URL", "").strip()

# Clean the URL if it has the 'vidyahu' prefix prepended by Render
if _raw_db_url.startswith("vidyahupostgres"):
    _raw_db_url = _raw_db_url.replace("vidyahu", "", 1)

# Use dj_database_url to parse the cleaned URL
if _raw_db_url.startswith(("postgres://", "postgresql://")):
    DATABASES['default'] = dj_database_url.config(
        default=_raw_db_url,
        conn_max_age=600,
        conn_health_checks=True,
    )
elif _raw_db_url:
    import warnings
    warnings.warn(f"DATABASE_URL is set but malformed. Falling back to SQLite.")





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AI Configuration
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
GROQ_API_KEY = os.getenv('GROQ_API_KEY')
CEREBRAS_API_KEY = os.getenv('CEREBRAS_API_KEY')
AI_SIMULATION_MODE = os.getenv('AI_SIMULATION_MODE', 'False').lower() == 'true'

# Redis Configuration (with fallback)
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# Socket.io Configuration
SOCKETIO_SERVER_URL = os.getenv('SOCKETIO_SERVER_URL', 'http://localhost:8000')

# CSRF Trusted Origins for all tunnel types and production
CSRF_TRUSTED_ORIGINS = [
    'https://*.loca.lt',
    'https://*.onrender.com',
    'https://*.lhr.life',
    'https://*.serveousercontent.com',
    'https://*.trycloudflare.com',   # Cloudflare Quick Tunnels (START_GLOBAL.bat)
]

# Dynamically add current tunnel URL from environment
if os.getenv('SOCKETIO_SERVER_URL'):
    url = os.getenv('SOCKETIO_SERVER_URL')
    if '.loca.lt' in url and url.startswith('http://'):
        url = url.replace('http://', 'https://')
    if url not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(url)


# Authentication URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'student_dashboard'
LOGOUT_REDIRECT_URL = 'index'
