import os
import sys
import django

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'vidyahub.settings')
django.setup()

from main.models import Grade, Subject, Chapter, MCQQuestion

g = Grade.objects.get(name='Class 11')
s = Subject.objects.get(name='Biology', grade=g)

chapters_pyqs = {
    "Cell Cycle and Cell Division": [
        ("Cell division is a form of:", "Binary fission", "Mitosis", "Meiosis", "Amitosis", "B", "Cell division through mitosis"),
        ("Mitosis was discovered by:", "Flemming", "Hertwig", "Strabburg", "Waldeyer", "A", "Flemming discovered mitosis"),
        ("In S-phase DNA content:", "Remains same", "Doubles", "Halves", "Triples", "B", "DNA doubles in S-phase"),
        ("Maximum time in cell cycle is spent in:", "Mitosis", "Interphase", "Cytokinesis", "Prophase", "B", "Most time in interphase"),
        ("Chromosomes condense in:", "Prophase", "Metaphase", "Anaphase", "Telophase", "A", "Chromosomes condense in prophase"),
        ("Centromere divides in:", "Prophase", "Metaphase", "Anaphase", "Telophase", "C", "Centromere divides in anaphase"),
        ("Cell plate forms in:", "Plants", "Animals", "Both", "None", "A", "Cell plate in plant cytokinesis"),
        ("Synapsis occurs in:", "Mitosis", "Meiosis I", "Meiosis II", "Interphase", "B", "Synapsis in meiosis I"),
        ("Crossing over occurs in:", "Leptotene", "Zygotene", "Pachytene", "Diplotene", "C", "Crossing over in pachytene"),
        ("Haploid cells are formed in:", "Mitosis", "Meiosis I", "Meiosis II", "Interphase", "C", "Meiosis II produces haploid"),
        ("Checkpoint for DNA replication is:", "G1", "G2", "S", "M", "B", "G2 checkpoint"),
        ("Cyclin was discovered by:", "Tyson", "Hunt", "Morgan", "Wilson", "B", "Hunt discovered cyclin"),
        ("Apoptosis is:", "Cell division", "Programmed cell death", "Cell growth", "Differentiation", "B", "Apoptosis is programmed death"),
        ("Cancer is due to:", "Overdivision", "Nodivision", "Different division", "Abnormal division", "A", "Cancer from uncontrolled division"),
        ("Meiosis results in:", "2 cells", "4 cells", "6 cells", "8 cells", "B", "Meiosis produces 4 cells"),
        ("Gametes are:", "Haploid", "Diploid", "Triploid", "Polyploid", "A", "Gametes are haploid"),
        ("Sister chromatids separate in:", "Prophase", "Metaphase", "Anaphase", "Telophase", "C", "Separation in anaphase"),
        ("Mitosis is for:", "Reproduction", "Growth", "Both A and B", "None", "C", "Mitosis for growth and repair"),
        ("Chiasmata are seen in:", "Mitosis", "Meiosis I", "Meiosis II", "Interphase", "B", "Chiasmata in meiosis I"),
        ("In oogenesis, polar bodies form in:", "Meiosis I", "Meiosis II", "Mitosis", "Interphase", "A", "Polar bodies in meiosis I"),
        ("Chromosomes become visible in:", "Interphase", "Prophase", "Metaphase", "Anaphase", "B", "Visible in prophase"),
        (" spindle fibers attach to:", "Kinetochore", "Centromere", "Chromatid", "Both A and B", "D", "Attach to kinetochore/centromere"),
        ("Anaphase promoting complex triggers:", "G1", "S", "M", "G2", "C", "APC triggers metaphase to anaphase"),
        ("Cytokinesis starts in:", "Prophase", "Metaphase", "Anaphase", "Telophase", "D", "Cytokinesis in telophase"),
        ("Cell cycle is controlled by:", "Genes", "Cyclins and CDKs", "Hormones", "All", "B", "Cyclins and CDKs control"),
        ("Meiosis I separates:", "Sister chromatids", "Homologous chromosomes", "Centromeres", "Chromatin", "B", "Homologous chromosomes separate"),
        ("Reduction division is:", "Mitosis", "Meiosis I", "Meiosis II", "Interphase", "B", "Meiosis I is reductional"),
        ("Spermatogenesis produces:", "1 sperm", "4 sperm", "2 sperm", "8 sperm", "B", "4 sperms from meiosis"),
        ("Growth factor affects:", "G1 phase", "G2 phase", "S phase", "M phase", "A", "GF affects G1 phase"),
        ("Terminal differentiation leads to:", "Cell division", "Cell death", "Cell cycle arrest", "Proliferation", "C", "Leads to cell cycle arrest"),
    ],
    "Transport in Plants": [
        ("Cohesion theory was given by:", "Dixon", "Jensen", " Crafts", "Ghosh", "A", "Dixon gave cohesion theory"),
        ("Water moves through:", "Xylem", "Phloem", "Cortex", "Epidermis", "A", "Water through xylem"),
        ("Root pressure is measured by:", "Manometer", "Potometer", "Barometer", "Psychrometer", "A", "Manometer measures root pressure"),
        ("Mycorrhiza helps in:", "Nitrogen fixation", "Water absorption", "Both A and B", "Protection", "B", "Mycorrhiza helps water absorption"),
        ("Stomatal transpiration is:", "50%", "70%", "90%", "30%", "C", "Stomatal 90% of transpiration"),
        ("Turgor pressure is:", "Positive", "Negative", "Neutral", "Zero", "A", "Turgor is positive pressure"),
        ("Apoplastic path is:", "Through cells", "Through cell walls", "Through plasmodesmata", "Through vacuoles", "B", "Apoplastic through cell walls"),
        ("Symplastic path is:", "Through cell walls", "Through cytoplasm", "Through vacuoles", "None", "B", "Symplastic through cytoplasm"),
        ("Guttation occurs due to:", "Transpiration", "Root pressure", "Capillarity", "Imbibition", "B", "Guttation from root pressure"),
        ("Wilting is due to:", "High turgor", "Low turgor", "No pressure", "High pressure", "B", "Wilting from low turgor"),
        ("Most water is lost through:", "Stomata", "Cuticle", "Lenticels", "Bark", "A", "Stomata 90% water loss"),
        ("Opening of stomata depends on:", "K+ ions", "Cl- ions", "Both A and B", "Na+ ions", "C", "K+ and Cl- for opening"),
        ("Abscisic acid causes:", "Stomatal opening", "Stomatal closure", "Growth", "Differentiation", "B", "ABA closes stomata"),
        ("Capsule of guard cells is:", "Cellulose", "Radial", "Both", "None", "B", "Radial micelles"),
        ("Guttation is seen in:", "Night", "Morning", "Afternoon", "Evening", "B", "Morning guttation"),
        ("Transpiration pull is due to:", "Cohesion", "Adhesion", "Capillarity", "All", "D", "All forces contribute"),
        ("Hertzberg experiment shows:", "Root pressure", "Transpiration pull", "Capillarity", "Cohesion", "B", "Transpiration pull"),
        ("Ascent of sap is due to:", "Root pressure", "Transpiration pull", "Capillarity", "All", "D", "Multiple forces"),
        ("Bleeding from cut stem is due to:", "Root pressure", "Transpiration", "Osmosis", "None", "A", "Root pressure causes bleeding"),
        ("Kentros has function:", "Water loss", "Water gain", "Photosynthesis", "Respiration", "A", "Kentros reduce water loss"),
        ("Aqua porins are:", "Proteins", "Lipids", "Carbohydrates", "Ions", "A", "Aqua porins are proteins"),
        ("Mesophyll cells have:", "High osmotic pressure", "Low osmotic pressure", "No pressure", "None", "A", "High osmotic in mesophyll"),
        ("Casparian strip is present in:", "Epidermis", "Endodermis", "Cortex", "Pericycle", "B", "Casparian in endodermis"),
        ("In symplast, movement is through:", "Cell walls", "Plasmodesmata", "Vacuoles", "Intercellular", "B", "Through plasmodesmata"),
        ("Aquatic plants lose water through:", "Stomata", "Cuticle", "Lenticels", "None", "D", "Aquatic plants little transpiration"),
        ("Raindrop effect is:", "Stomata open", "Stomata close", "No effect", "Cuticle", "A", "Rain opens stomata"),
        ("Potometer measures:", "Transpiration", "Absorption", "Root pressure", "Capillarity", "A", "Potometer measures transpiration"),
        ("Anti-transpirants are:", "PMA", "ABA", "Both A and B", "None", "C", "Both reduce transpiration"),
        ("Bulk flow occurs in:", "Xylem", "Phloem", "Sieve tubes", "Cortex", "A", "Bulk flow in xylem"),
        ("In vines, water conduction is through:", "Wide xylem", "Narrow xylem", "Phloem", "None", "A", "Wide xylem in vines"),
    ],
    "Mineral Nutrition": [
        ("Essential elements were given by:", "Arnon", "Stout", "Hoagland", "Dickson", "A", "Arnon gave essential elements"),
        ("Nitrogen is essential for:", "Leaf growth", "Root growth", "Protein synthesis", "All", "D", "N for proteins, nucleic acids"),
        ("Iron is important for:", "Chlorophyll", "Nucleic acids", "Enzyme cofactor", "Vitamins", "C", "Iron as enzyme cofactor"),
        ("Magnesium is part of:", "Chlorophyll", "DNA", "RNA", "Protein", "A", "Mg part of chlorophyll"),
        ("Potassium is needed for:", "Stomatal function", "Nodule formation", "Photosynthesis", "Respiration", "A", "K for stomatal opening"),
        ("Calcium is important for:", "Cell wall", "Membrane", "Enzymes", "All", "D", "Ca for cell wall, membranes"),
        ("Zinc is component of:", "Chlorophyll", "Enzymes", "Hormones", "All", "B", "Zn in many enzymes"),
        ("Manganese is needed for:", "N2 fixation", "Photosystem II", "Respiration", "Mineralization", "B", "Mn for PSII"),
        ("Copper is component of:", "Plastocyanin", "Ferredoxin", "Hydrogenase", "Nitrogenase", "A", "Cu in plastocyanin"),
        ("Molybdenum is needed for:", "Nodulation", "Nitrate reduction", "N2 fixation", "Denitrification", "B", "Mo for nitrate reduction"),
        ("Chlorine is needed for:", "Photosynthesis", "Respiration", "Growth", "All", "A", "Cl for photosynthesis"),
        ("Boron is needed for:", "Membrane function", "Pollentube growth", "Cell division", "All", "D", "B for membrane, pollen"),
        ("Essential elements are:", "16", "17", "18", "20", "A", "16 essential elements"),
        ("Mobile elements in plants:", "N, P, K", "Ca, Mg", "S, Fe", "All", "A", "N, P, K mobile"),
        ("Nitrogen fixation needs:", "Mo", "Co", "Ni", "W", "A", "Mo for N-fixation"),
        ("Sulphur is part of:", "Proteins", "CoA", "Both A and B", "Vitamins", "C", "S in proteins and CoA"),
        ("Sodium is needed by:", "Plants", "Animals", "Both", "None", "C", "Na for both"),
        ("Silicon is important for:", "Cell strength", "Growth", "Reproduction", "None", "A", "Si for cell strength"),
        ("Nickel is needed for:", "Urease activity", "Nodulation", "Photosynthesis", "Respiration", "A", "Ni for urease"),
        ("Heavy metals are toxic:", "Cu", "Zn", "Hg", "Fe", "C", "Hg is toxic"),
        ("Deficiency of N causes:", "Chlorosis", "Necrosis", "Anthocyanin", "Brittleness", "A", "N deficiency chlorosis"),
        ("Iron deficiency causes:", "Interveinal chlorosis", "Necrosis", "Curling", "Stunting", "A", "Fe chlorosis interveinal"),
        ("Potassium deficiency shows:", "Marginal chlorosis", "Necrotic spots", "Stunted growth", "All", "D", "K deficiency multiple symptoms"),
        ("Zinc deficiency causes:", "Little leaf", "Rosetting", "Both A and B", "None", "C", "Zn deficiency little leaf"),
        ("Magnesium deficiency shows:", "Interveinal chlorosis", "Necrosis", "Reddening", "All", "A", "Mg chlorosis similar to Fe"),
        ("Manganese deficiency appears like:", "Iron deficiency", "Zinc deficiency", "Copper deficiency", "None", "A", "Mn deficiency similar to Fe"),
        ("Toxicity is common in:", "Iron", "Manganese", "Zinc", "All", "D", "Multiple elements toxic"),
        ("Fertilizers contain:", "N, P, K", "Ca, Mg", "S, micronutrients", "All", "D", "Fertilizers have all"),
        ("Hydroponics was discovered by:", "Gericke", "Hoagland", "Arnon", "Stout", "A", "Gericke developed hydroponics"),
        ("Chlorosis is:", "Loss of chlorophyll", "Necrosis", "Brittleness", "Curling", "A", "Chlorosis loss of green"),
    ],
    "Photosynthesis in Higher Plants": [
        ("Father of photosynthesis is:", "Junior", "Engelmann", "Ingenhousz", "Sachs", "C", "Ingenhousz discovered photosynthesis"),
        ("First product of photosynthesis is:", "Starch", "Sugar", "Oxygen", "Water", "B", "First product is sugar"),
        ("Light reactions occur in:", "Stroma", "Thylakoid membrane", "Cytoplasm", "Nucleus", "B", "Light reactions in thylakoids"),
        ("Dark reactions occur in:", "Stroma", "Thylakoid", "Membrane", "Intermembrane", "A", "Dark reactions in stroma"),
        ("Chlorophyll is located in:", "Stroma", "Thylakoid membrane", "Grana", "Lamellae", "B", "Chlorophyll in thylakoid"),
        ("Photolysis of water occurs in:", "PS I", "PS II", "Both", "None", "B", "Photolysis in PSII"),
        ("Oxygen evolved in photosynthesis comes from:", "CO2", "Water", "Mineral", "Air", "B", "Oxygen from water"),
        ("Primary acceptor of CO2 is:", "RUBP", "RuBP", "Malic acid", "PEP", "B", "RuBP is CO2 acceptor"),
        ("C3 plants are:", "Wheat", "Rice", "Both A and B", "None", "C", "Wheat and rice C3"),
        ("C4 plants have:", "One cell", "Two cells", "No cells", "Three cells", "B", "Kranz anatomy two cells"),
        ("In C4 pathway, primary CO2 acceptor is:", "RUBP", "PEP", "Malate", "Aspartate", "B", "PEP is acceptor"),
        ("PEP carboxylase is in:", "Mesophyll", "Bundle sheath", "Both", "None", "A", "PEP in mesophyll"),
        ("CAM plants open stomata:", "Day", "Night", "Both", "None", "B", "CAM open at night"),
        ("Photophosphorylation occurs in:", "Stroma", "Thylakoid", "Cytoplasm", "Nucleus", "B", "In thylakoid membrane"),
        ("ATP synthase is located in:", "Stroma", "Thylakoid membrane", "Grana", "Intergrana", "B", "ATP synthase in thylakoid"),
        ("Chlorophyll a absorbs:", "Red and blue", "Green", "Yellow", "All", "A", "Chlorophyll a red and blue"),
        ("Chlorophyll b absorbs:", "Red and blue", "Green", "Yellow", "All", "A", "Chlorophyll b blue"),
        ("Photorespiration occurs in:", "C4 plants", "C3 plants", "CAM plants", "All", "B", "Photorespiration in C3"),
        ("Warburg effect is:", "Low O2 inhibits photosynthesis", "CO2 inhibits photosynthesis", "High O2 inhibits", "None", "C", "High O2 inhibits"),
        ("Calvin cycle occurs in:", "Stroma", "Thylakoid", "Membrane", "Cytoplasm", "A", "Calvin in stroma"),
        ("PGAL is formed in:", "Reduction phase", "Regeneration phase", "Carbon fixation", "All", "A", "PGAL in reduction"),
        ("Rubisco is:", "Protease", "Carboxylase", "Oxidase", "None", "B", "Rubisco is carboxylase"),
        ("Non-cyclic photophosphorylation produces:", "ATP", "NADPH", "O2", "All", "D", "Produces ATP, NADPH, O2"),
        ("Cyclic photophosphorylation produces:", "ATP", "NADPH", "O2", "All", "A", "Produces only ATP"),
        ("Quantum yield is:", "1/8", "1/12", "1/4", "1/2", "A", "Quantum yield 1/8"),
        ("Blackman's law is about:", "Limiting factors", "Light intensity", "CO2 concentration", "Temperature", "A", "Limiting factor law"),
        ("Phloem loads:", "Active transport", "Passive transport", "Both", "None", "A", "Phloem active loading"),
        ("Phloem unloads:", "Active transport", "Passive transport", "Both", "None", "B", "Passive unloading"),
        ("Source is:", "Leaf", "Root", "Stem", "All", "A", "Source is photosynthesizing leaf"),
        ("Sink is:", "Root", "Stem", "Developing organs", "All", "D", "Sink is growing parts"),
    ],
    "Respiration in Plants": [
        ("Respiration was discovered by:", "Lavoisier", "Black", "Priestley", "Ingenhousz", "A", "Lavoisier discovered respiration"),
        ("First step of glycolysis is:", "Glucose to G6P", "Glucose to F6P", "Glucose to G3P", "None", "A", "Glucose to glucose-6-phosphate"),
        ("Pyruvate is formed in:", "Cytoplasm", "Mitochondria", "Nucleus", "Cell wall", "A", "Pyruvate in cytoplasm"),
        ("Krebs cycle occurs in:", "Cytoplasm", "Mitochondrial matrix", "Inner membrane", "Outer membrane", "B", "Krebs in mitochondrial matrix"),
        ("Electron transport chain is in:", "Cytoplasm", "Inner mitochondrial membrane", "Outer membrane", "Matrix", "B", "ETC in inner membrane"),
        ("ATP yield from one glucose is:", "2", "30", "36", "38", "D", "Theoretical 38 ATP"),
        ("Fermentation occurs in:", "Mitochondria", "Cytoplasm", "Nucleus", "Cell wall", "B", "Fermentation in cytoplasm"),
        ("Lactate fermentation produces:", "Lactate", "Ethanol", "CO2", "Both A and B", "A", "Lactate from lactate fermentation"),
        ("Alcoholic fermentation produces:", "Lactate", "Ethanol", "CO2", "Both B and C", "D", "Ethanol + CO2"),
        ("Anaerobic respiration produces:", "36 ATP", "2 ATP", "4 ATP", "8 ATP", "B", "Anaerobic only 2 ATP"),
        ("RQs for carbohydrates is:", "1.0", "0.7", "1.5", "0.5", "A", "RQ of glucose is 1"),
        ("RQ of fat is:", "1.0", "0.7", "1.5", "0.5", "B", "RQ of fat is 0.7"),
        ("RQ of protein is:", "1.0", "0.8", "0.9", "0.7", "C", "RQ of protein ~0.8"),
        ("Cytochrome is:", "Carbohydrate", "Protein", "Lipid", "Nucleic acid", "B", "Cytochrome is a protein"),
        ("Decarboxylation occurs in:", "Glycolysis", "Link reaction", "Krebs cycle", "All", "D", "Decarboxylation in multiple steps"),
        ("Dehydrogenase removes:", "CO2", "H+", "O2", "Electrons", "D", "Dehydrogenase removes H"),
        ("OAA is formed in:", "Glycolysis", "Link reaction", "Krebs cycle", "None", "C", "OAA in Krebs cycle"),
        ("Succinate dehydrogenase is in:", "Cytoplasm", "Inner membrane", "Outer membrane", "Matrix", "B", "Succinate DH in inner membrane"),
        ("Malate dehydrogenase forms:", "OAA", "Succinate", "Fumarate", "Malate", "A", "Forms OAA"),
        ("Glycolysis requires:", "O2", "No O2", "CO2", "None", "B", "Anaerobic glycolysis"),
        ("Pasteur effect is:", "Inhibition by O2", "Stimulation by O2", "No effect", "None", "A", "O2 inhibits fermentation"),
        ("Cyanide inhibits:", "Glycolysis", "Krebs cycle", "ETC", "Fermentation", "C", "Inhibits cytochrome oxidase"),
        ("Malonate inhibits:", "Succinate dehydrogenase", "Cytochrome oxidase", "ATP synthase", "None", "A", "Inhibits SDH"),
        ("DNP uncouples:", "Oxidative phosphorylation", "Photophosphorylation", "Substrate level", "None", "A", "Uncouples ETC"),
        ("ATP is produced in:", "Glycolysis", "Krebs cycle", "ETC", "All", "D", "ATP from all processes"),
        ("Substrate level phosphorylation in:", "Glycolysis", "Krebs cycle", "Both", "None", "C", "Both glycolysis and Krebs"),
        ("Oxidative phosphorylation produces:", "2 ATP", "34 ATP", "36 ATP", "18 ATP", "B", "Oxidative makes 34 ATP"),
        ("Anaerobic respiration is:", "Inefficient", "Efficient", "No ATP", "None", "A", "Inefficient - 2 ATP vs 38"),
        ("Cytochrome oxidase is:", "Cytochrome a", "Cytochrome c", "Cytochrome b", "Cytochrome a3", "D", "Cytochrome a3 is final"),
        ("Alternative oxidase is in:", "Plants", "Animals", "Both", "None", "A", "Alternative oxidase in plants"),
    ],
    "Plant Growth and Development": [
        ("Plant growth is:", "Limited", "Unlimited", "Both", "None", "B", "Plants have unlimited growth"),
        ("Plant growth is measured by:", "Length", "Mass", "Both A and B", "None", "C", "Both length and mass"),
        ("Growth curve is:", "Linear", "Sigmoid", "Exponential", "Logarithmic", "B", "Sigmoid growth curve"),
        ("Phase of rapid growth is:", "Lag phase", "Log phase", "Stationary phase", "None", "B", "Log phase rapid"),
        ("Grand period is:", "Phase", "Period of growth", "Growth curve", "Growth rate", "B", "Grand period is growth period"),
        ("Absolute growth rate is:", "Per unit time", "Per unit size", "Per plant", "None", "A", "AGR per unit time"),
        ("Relative growth rate is:", "Per unit time", "Per unit size", "Both A and B", "None", "C", "RGR per unit size per time"),
        ("Phytohormones are:", "Growth regulators", "Growth inhibitors", "Both A and B", "None", "A", "Plant hormones"),
        ("Auxin was discovered by:", "Darwin", "Went", "Miller", "Sachs", "B", "Went discovered auxin"),
        ("Apical dominance is due to:", "Cytokinin", "Auxin", "Gibberellin", "ABA", "B", "Auxin causes apical dominance"),
        ("Gibberellin was discovered from:", "Rice", "Wheat", "Barley", "Maize", "A", "Gibberellin from rice fungus"),
        ("Abscisic acid causes:", "Growth", "Dormancy", "Senescence", "None", "B", "ABA induces dormancy"),
        ("Cytokinin promotes:", "Cell division", "Cell elongation", "Cell differentiation", "All", "D", "Cytokinin does all"),
        ("Ethylene causes:", "Fruit ripening", "Leaf abscission", "Senescence", "All", "D", "Ethylene has multiple effects"),
        ("Phototropism is due to:", "Auxin", "Gibberellin", "Cytokinin", "ABA", "A", "Auxin causes phototropism"),
        ("Gravitropism is due to:", "Auxin", "Gibberellin", "Cytokinin", "Ethylene", "A", "Auxin redistribution"),
        ("Thigmotropism is response to:", "Light", "Gravity", "Touch", "Water", "C", "Response to touch"),
        ("Vernalization is response to:", "Light", "Temperature", "Photoperiod", "Water", "B", "Response to cold"),
        ("Florigen is:", "Protein", "Hormone", "Gene", "None", "A", "Florigen is protein"),
        ("Short day plants flower in:", "Long nights", "Short nights", "Any day", "None", "A", "Flower in long nights"),
        ("Long day plants flower in:", "Long nights", "Short nights", "Any day", "None", "B", "Flower in short nights"),
        ("Day neutral plants flower in:", "Any day", "Particular day", "No day", "None", "A", "Flower in any day"),
        ("Critical photoperiod is:", "Maximum hours", "Minimum hours", "Threshold hours", "None", "C", "Critical day length"),
        ("Phytochrome is:", "Protein", "Lipid", "Carbohydrate", "Nucleic acid", "A", "Phytochrome is protein"),
        ("Pr form absorbs:", "Red", "Far red", "Blue", "Green", "A", "Pr absorbs red light"),
        ("Pfr form absorbs:", "Red", "Far red", "Blue", "Green", "B", "Pfr absorbs far red"),
        ("Leaf senescence is due to:", "Ethylene", "Cytokinin", "ABA", "All", "D", "Multiple hormones"),
        ("Skl gene is activated by:", "Auxin", "Cytokinin", "Gibberellin", "All", "A", "Skl by auxin"),
        ("Seed dormancy is broken by:", "Gibberellin", "Cytokinin", "Ethylene", "All", "A", "Gibberellin breaks dormancy"),
        ("Somaclonal variation occurs in:", "Tissue culture", "Seeds", "Cuttings", "None", "A", "Variation in tissue culture"),
    ],
}

for chapter_name, pyqs in chapters_pyqs.items():
    try:
        c = Chapter.objects.get(subject=s, name=chapter_name)
        MCQQuestion.objects.filter(chapter=c).delete()
        for order, q in enumerate(pyqs):
            MCQQuestion.objects.create(
                chapter=c,
                question_text=q[0],
                option_a=q[1],
                option_b=q[2],
                option_c=q[3],
                option_d=q[4],
                correct_option=q[5],
                explanation=q[6],
                order=order
            )
        print(f"Added {len(pyqs)} PYQs to {chapter_name}")
    except Chapter.DoesNotExist:
        print(f"Chapter {chapter_name} not found")
    except Exception as e:
        print(f"Error with {chapter_name}: {e}")

print("\nDone adding more chapters")