import os
import sys
import django

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'vidyahub.settings')
django.setup()

from main.models import Grade, Subject, Chapter, MCQQuestion

g = Grade.objects.get(name='Class 11')
s = Subject.objects.get(name='Biology', grade=g)

chapters_pyqs = {
    "Digestion and Absorption": [
        ("Digestion occurs in:", "Stomach", "Small intestine", "Buccal cavity", "All", "D", "Digestion in multiple organs"),
        ("Maximum digestion occurs in:", "Stomach", "Small intestine", "Large intestine", "Buccal cavity", "B", "Small intestine max digestion"),
        ("Bile emulsifies:", "Proteins", "Fats", "Carbohydrates", "All", "B", "Bile emulsifies fats"),
        ("Pepsin acts on:", "Proteins", "Fats", "Carbohydrates", "Lipids", "A", "Pepsin digests proteins"),
        ("Trypsin is activated by:", "HCl", "Enterokinase", "Bile", "Lipase", "B", "Enterokinase activates trypsin"),
        ("Maltose is digested by:", "Maltase", "Sucrase", "Lactase", "All", "A", "Maltase digests maltose"),
        ("Maximum absorption occurs in:", "Stomach", "Duodenum", "Jejunum", "Ileum", "C", "Jejunum maximum absorption"),
        ("Chylomicrons are absorbed by:", "Blood", "Lymph", "Both", "None", "B", "Chylomicrons in lymph"),
        ("Villi are found in:", "Stomach", "Small intestine", "Large intestine", "All", "B", "Villi in small intestine"),
        ("Peyer's patches are in:", "Duodenum", "Jejunum", "Ileum", "Stomach", "C", "Peyer's patches in ileum"),
        ("Crypts of Lieberkuhn are in:", "Stomach", "Small intestine", "Large intestine", "All", "B", "Crypts in small intestine"),
        ("Glucose is absorbed by:", "Simple diffusion", "Facilitated diffusion", "Active transport", "Both B and C", "D", "Glucose by facilitated and active"),
        ("Amino acids are absorbed by:", "Simple diffusion", "Facilitated diffusion", "Active transport", "Both B and C", "D", "Amino acids by facilitated and active"),
        ("Fatty acids are absorbed by:", "Blood", "Lymph", "Both", "None", "B", "Fatty acids in lymph"),
        ("Vitamin B12 is absorbed in:", "Stomach", "Duodenum", "Ileum", "Jejunum", "C", "Vitamin B12 in ileum"),
        ("Intrinsic factor is secreted by:", "Chief cells", "Parietal cells", "G cells", "Mucous cells", "B", "Parietal cells secrete IF"),
        ("HCl is secreted by:", "Chief cells", "Parietal cells", "G cells", "Mucous cells", "B", "Parietal cells secrete HCl"),
        ("Gastrin is secreted by:", "Chief cells", "Parietal cells", "G cells", "Mucous cells", "C", "G cells secrete gastrin"),
        ("Secretin is released by:", "Stomach", "Duodenum", "Jejunum", "Ileum", "B", "Secretin from duodenum"),
        ("CCK is released by:", "Stomach", "Duodenum", "Jejunum", "Ileum", "B", "CCK from duodenum"),
        ("Sucrose is digested into:", "Glucose", "Fructose", "Both A and B", "None", "C", "Sucrose to glucose and fructose"),
        ("Lactose is digested into:", "Glucose", "Galactose", "Both A and B", "None", "C", "Lactose to glucose galactose"),
        ("Lipase digests:", "Triglycerides", "Proteins", "Carbohydrates", "All", "A", "Lipase digests triglycerides"),
        ("Amylase digests:", "Starch", "Proteins", "Fats", "All", "A", "Amylase digests starch"),
        ("Intestinal brush border has:", "Enzymes", "Transporters", "Both A and B", "None", "C", "Brush border has both"),
        ("Peristalsis is:", "Voluntary", "Involuntary", "Both", "None", "B", "Peristalsis is involuntary"),
        ("MMP is:", "Protease", "Lipase", "Carbohydrase", "All", "A", "MMP is proteolytic enzyme"),
        ("Rennin acts on:", "Proteins", "Casein", "Fats", "All", "B", "Rennin coagulates casein"),
        ("Calmodulin is:", "Protein", "Carbohydrate", "Lipid", "Ion", "A", "Calmodulin is calcium protein"),
        ("Basal metabolic rate is measured by:", "BMI", "BMR", "GA", "GH", "B", "BMR basal metabolic rate"),
    ],
    "Breathing and Exchange of Gases": [
        ("Respiration is:", "External", "Internal", "Cellular", "All", "D", "All three types"),
        ("Anatomical respiratory tract includes:", "Nose", "Pharynx", "Larynx", "All", "D", "All parts of tract"),
        ("Trachea divides into:", "2 bronchi", "3 bronchi", "4 bronchi", "5 bronchi", "A", "Trachea into 2 bronchi"),
        ("Surfactant is secreted by:", "Type I pneumocytes", "Type II pneumocytes", "Alveolar macrophages", "Clara cells", "B", "Type II cells secrete surfactant"),
        ("Surfactant reduces:", "Surface tension", "Respiration", "Diffusion", "None", "A", "Surfactant reduces surface tension"),
        ("Vital capacity is:", "TV + IRV + ERV", "TV + IRV", "IRV + ERV", "None", "A", "VC = TV + IRV + ERV"),
        ("Residual volume is:", "500 ml", "1000 ml", "1500 ml", "1200 ml", "D", "Residual volume ~1200 ml"),
        ("Tidal volume is:", "350 ml", "450 ml", "500 ml", "250 ml", "C", "Tidal volume ~500 ml"),
        ("Dead space is:", "150 ml", "350 ml", "500 ml", "250 ml", "A", "Anatomical dead space 150 ml"),
        ("Henry's law is about:", "Gas pressure", "Gas solubility", "Gas diffusion", "Gas exchange", "B", "Gas solubility"),
        ("Bohr effect is:", "O2 affinity", "CO2 transport", "pH effect", "All", "D", "Bohr effect relates pH to O2"),
        ("Haldane effect is:", "O2 transport", "CO2 transport", "pH effect", "All", "B", "Haldane effect on CO2"),
        ("O2 is carried by:", "Hemoglobin", "Myoglobin", "Both A and B", "None", "C", "Both Hb and Mb"),
        ("CO2 is carried as:", "Bicarbonate", "Carbaminohemoglobin", "Dissolved", "All", "D", "All three forms"),
        ("Carbonic anhydrase is in:", "RBCs", "Lungs", "Tissues", "All", "D", "Carbonic anhydrase everywhere"),
        ("O2 dissociation curve is:", "Sigmoid", "Hyperbolic", "Linear", "Exponential", "A", "Sigmoid O2 dissociation"),
        ("P50 is:", "O2 at 50% saturation", "Partial pressure", "Both A and B", "None", "C", "P50 is partial pressure"),
        ("Hypoxia occurs due to:", "Low O2", "Low Hb", "Low circulation", "All", "D", "Multiple causes"),
        ("Apnea is:", "No breathing", "Difficult breathing", "Shallow breathing", "None", "A", "Apnea is no breathing"),
        ("Dyspnea is:", "Breathlessness", "Painful breathing", "Difficulty in breathing", "None", "C", "Dyspnea difficult breathing"),
        ("Orthopnea is:", "Breathing while standing", "Breathing while sitting", "Breathing while lying", "None", "C", "Orthopnea when lying"),
        ("Eupnea is:", "Abnormal breathing", "Normal breathing", "Difficult breathing", "None", "B", "Eupnea is normal"),
        ("Cheyne-Stokes is:", "Normal", "Periodic", "Abnormal", "None", "B", "Cheyne-Stokes periodic breathing"),
        ("Wheezing is due to:", "Narrow airways", "Wide airways", "Fluid", "None", "A", "Narrow airways cause wheeze"),
        ("Cyanosis is due to:", "Low O2", "Low Hb", "High CO2", "All", "A", "Cyanosis from low O2"),
        ("Clubbing is due to:", "Lung disease", "Heart disease", "Liver disease", "None", "A", "Clubbing with lung disease"),
        ("FVC is:", "Forced vital capacity", "Functional volume", "Foreign vocabulary", "None", "A", "FVC forced vital capacity"),
        ("FEV1 is:", "Forced expired volume in 1 sec", "Functional expired", "Foreign expired", "None", "A", "FEV1 forced expired volume"),
        ("DLCO is:", "Diffusing capacity", "Lung volume", "Airway resistance", "None", "A", "DLCO diffusing capacity"),
        ("Respiratory center is in:", "Cerebrum", "Cerebellum", "Medulla and pons", "Hypothalamus", "C", "Medulla and pons"),
    ],
    "Body Fluids and Circulation": [
        ("Blood is a:", "Tissue", "Organ", "System", "None", "A", "Blood is connective tissue"),
        ("Plasma constitutes:", "45%", "55%", "65%", "75%", "B", "Plasma ~55%"),
        ("RBC count in males is:", "4.5-5.5 million", "3.5-4.5 million", "5.5-6.5 million", "None", "A", "Males 4.5-5.5 million"),
        ("WBC count is:", "6000-10000", "4000-11000", "5000-9000", "None", "B", "WBC 4000-11000"),
        ("Platelets count is:", "1.5-3.5 lakh", "1-3 lakh", "2-4 lakh", "None", "A", "Platelets 1.5-3.5 lakh"),
        ("Hemoglobin in males is:", "13-17 g%", "12-16 g%", "14-18 g%", "None", "C", "Males 14-18 g%"),
        ("ESR is measured by:", "Wintrobe", "Westergren", "Both A and B", "None", "C", "Both methods"),
        ("Blood group is determined by:", "Antigens", "Antibodies", "Both A and B", "None", "A", "Blood groups by antigens"),
        ("Rh factor was discovered in:", "1940", "1930", "1950", "1960", "A", "Rh discovered 1940"),
        ("Universal donor is:", "O-", "O+", "AB+", "AB-", "A", "O- universal donor"),
        ("Universal recipient is:", "O-", "O+", "AB+", "AB-", "C", "AB+ universal recipient"),
        ("Erythroblastosis fetalis occurs due to:", "Rh incompatibility", "ABO incompatibility", "Both A and B", "None", "A", "Rh incompatibility"),
        ("Hematocrit is:", "RBC volume", "Plasma volume", "Platelet volume", "None", "A", "Hematocrit RBC volume"),
        ("Serum is:", "Plasma without fibrinogen", "Plasma with fibrinogen", "Blood with cells", "None", "A", "Serum plasma without fibrinogen"),
        ("ANP is secreted by:", "Kidneys", "Heart", "Liver", "Lungs", "B", "ANP from heart atria"),
        ("BNP is secreted by:", "Kidneys", "Heart", "Liver", "Lungs", "B", "BNP from heart ventricles"),
        ("Thromboxane promotes:", "Vasodilation", "Vasoconstriction", "No effect", "None", "B", "Thromboxane vasoconstriction"),
        ("Prostacyclin causes:", "Vasoconstriction", "Vasodilation", "No effect", "None", "B", "Prostacyclin vasodilation"),
        ("Heparin is secreted by:", "Liver", "Lungs", "Mast cells", "All", "C", "Heparin from mast cells"),
        ("Fibrinogen is converted to fibrin by:", "Thrombin", "Plasmin", "TPA", "None", "A", "Thrombin converts fibrinogen"),
        ("Cardiac muscle is:", "Striated voluntary", "Striated involuntary", "Smooth involuntary", "None", "B", "Cardiac striated involuntary"),
        ("Sinoatrial node is located in:", "Right atrium", "Left atrium", "Ventricle", "None", "A", "SA node in right atrium"),
        ("AV node is located in:", "Right atrium", "Left atrium", "Ventricle", "None", "A", "AV node near septum"),
        ("Purkinje fibers are in:", "Atria", "Ventricles", "Both", "None", "B", "Purkinje in ventricles"),
        ("TPR is:", "Total peripheral resistance", "Total pulmonary resistance", "Tissue perfusion rate", "None", "A", "TPR total peripheral resistance"),
        ("MAP is:", "Mean arterial pressure", "Maximum arterial pressure", "Minimum arterial pressure", "None", "A", "MAP mean arterial pressure"),
        ("Systolic pressure is:", "120 mmHg", "110 mmHg", "130 mmHg", "100 mmHg", "A", "Systolic ~120 mmHg"),
        ("Diastolic pressure is:", "80 mmHg", "70 mmHg", "90 mmHg", "60 mmHg", "A", "Diastolic ~80 mmHg"),
        ("Junctional rhythm is:", "40-60 bpm", "60-100 bpm", "100-140 bpm", "None", "A", "Junctional 40-60 bpm"),
        ("First heart sound is:", "Lub", "Dub", "Lub-dub", "None", "A", "First sound lub"),
    ],
    "Excretory Products and their Elimination": [
        ("Ammonotelism is seen in:", "Mammals", "Birds", "Aquatic animals", "Reptiles", "C", "Aquatic animals excrete ammonia"),
        ("Ureotelism is seen in:", "Mammals", "Fishes", "Birds", "Reptiles", "A", "Mammals excrete urea"),
        ("Uricotelism is seen in:", "Mammals", "Birds", "Fishes", "Amphibians", "B", "Birds excrete uric acid"),
        ("Kidney is located at:", "T12-L3", "T10-L2", "L1-L4", "None", "A", "Kidney T12-L3"),
        ("Nephron is functional unit of:", "Liver", "Kidney", "Heart", "Lungs", "B", "Nephron is kidney's unit"),
        ("Juxtaglomerular apparatus is in:", "Cortex", "Medulla", "Pyramid", "None", "A", "JGA in cortex"),
        ("Glomerular filtration rate is:", "125 ml/min", "180 ml/min", "100 ml/min", "None", "A", "GFR 125 ml/min"),
        ("Tubular reabsorption occurs in:", "Proximal tubule", "Loop of Henle", "Distal tubule", "All", "D", "Reabsorption throughout"),
        ("Maximum reabsorption occurs in:", "Proximal tubule", "Loop of Henle", "Distal tubule", "Collecting duct", "A", "Proximal tubule 65%"),
        ("ADH acts on:", "Proximal tubule", "Loop of Henle", "Distal tubule", "Collecting duct", "D", "ADH on collecting duct"),
        ("Aldosterone acts on:", "Proximal tubule", "Loop of Henle", "Distal tubule", "Collecting duct", "C", "Aldosterone on distal tubule"),
        ("Renin is secreted by:", "Macula densa", "Juxtaglomerular cells", "Mesangial cells", "All", "B", "Renin from JG cells"),
        ("Erythropoietin is secreted by:", "Liver", "Kidney", "Bone marrow", "Both A and B", "D", "Erythropoietin from liver and kidney"),
        ("Calcitriol is activated in:", "Liver", "Kidney", "Intestine", "All", "D", "Calcitriol activation in multiple"),
        ("Micturition is controlled by:", "Cerebrum", "Cerebellum", "Spinal cord", "All", "A", "Micturition by brain"),
        ("Bladder capacity is:", "350-400 ml", "450-500 ml", "250-300 ml", "None", "B", "Bladder 450-500 ml"),
        ("Detrusor muscle is in:", "Bladder wall", "Ureter", "Urethra", "None", "A", "Detrusor in bladder wall"),
        ("Internal urethral sphincter is:", "Voluntary", "Involuntary", "Both", "None", "B", "Internal sphincter involuntary"),
        ("External urethral sphincter is:", "Voluntary", "Involuntary", "Both", "None", "A", "External sphincter voluntary"),
        ("Hemodialysis is done in:", "Kidney failure", "Liver failure", "Heart failure", "None", "A", "Hemodialysis kidney failure"),
        ("Peritoneal dialysis uses:", "Peritoneal cavity", "Blood", "Intestine", "None", "A", "Peritoneal cavity"),
        ("Kidney stones are composed of:", "Calcium oxalate", "Uric acid", "Cystine", "All", "D", "Multiple compositions"),
        ("Creatinine is from:", "Protein metabolism", "Carbohydrate metabolism", "Fat metabolism", "None", "A", "Creatinine from protein"),
        ("Blood urea is measured by:", "Berthelot method", "Folin method", "Both A and B", "None", "C", "Multiple methods"),
        ("Urea synthesis occurs in:", "Liver", "Kidney", "Both A and B", "None", "C", "Urea in liver and kidney"),
        ("Countercurrent multiplier is in:", "Loop of Henle", "Distal tubule", "Collecting duct", "None", "A", "Countercurrent in loop"),
        ("Vasa recta is in:", "Cortex", "Medulla", "Pyramid", "None", "B", "Vasa recta in medulla"),
        ("JGA maintains:", "Glomerular filtration", "Tubular secretion", "Reabsorption", "All", "A", "JGA maintains GFR"),
        ("ANP promotes:", "Na+ excretion", "Na+ reabsorption", "K+ excretion", "None", "A", "ANP promotes Na+ excretion"),
        ("Countercurrent exchanger is in:", "Vasa recta", "Loop of Henle", "Collecting duct", "None", "A", "Countercurrent in vasa recta"),
    ],
    "Locomotion and Movement": [
        ("Skeletal muscle is:", "Voluntary", "Involuntary", "Cardiac", "Smooth", "A", "Skeletal muscle voluntary"),
        ("Muscle contraction needs:", "Ca2+", "ATP", "Both A and B", "None", "C", "Ca2+ and ATP needed"),
        ("Actin filament is attached to:", "Z line", "M line", "H zone", "None", "A", "Actin attached to Z line"),
        ("Myosin head has:", "ATPase", "Kinase", "Phosphatase", "None", "A", "Myosin has ATPase"),
        ("Power stroke is due to:", "ATP hydrolysis", "Ca2+ release", "Action potential", "None", "A", "Power stroke ATP hydrolysis"),
        ("Sliding filament theory was given by:", "Huxley", "Hill", "Meyerhof", "Krebs", "A", "Huxley sliding filament"),
        ("Tropomyosin blocks:", "Actin binding sites", "Myosin binding sites", "ATP binding sites", "None", "B", "Tropomyosin blocks myosin sites"),
        ("Troponin binds to:", "Actin", "Myosin", "Tropomyosin", "All", "A", "Troponin binds actin"),
        ("Neuromuscular junction is:", "Chemical synapse", "Electrical synapse", "Both", "None", "A", "Neuromuscular is chemical"),
        ("ACh is broken by:", "Acetylcholinesterase", "Choline acetyltransferase", "Both", "None", "A", "AChE breaks ACh"),
        ("Muscle fatigue is due to:", "Lactic acid", "ADP", "Both A and B", "None", "C", "Lactic acid and ADP"),
        ("Rigor mortis is due to:", "ATP deficiency", "Ca2+ excess", "Both A and B", "None", "C", "ATP deficiency and Ca2+"),
        ("Red fibers have:", "More mitochondria", "Few mitochondria", "No mitochondria", "None", "A", "Red fibers more mitochondria"),
        ("White fibers have:", "More mitochondria", "Few mitochondria", "No mitochondria", "B", "White fibers few mitochondria"),
        ("Slow fibers are:", "Type I", "Type II", "Type III", "None", "A", "Slow fibers Type I"),
        ("Fast fibers are:", "Type I", "Type II", "Type III", "B", "Fast fibers Type II"),
        ("Isometric contraction is:", "Length constant", "Tension constant", "Both", "None", "B", "Isometric tension constant"),
        ("Isotonic contraction is:", "Length constant", "Tension constant", "Both", "None", "A", "Isotonic length constant"),
        ("Synergistic muscles:", "Work together", "Work opposite", "No effect", "None", "A", "Synergists work together"),
        ("Antagonistic muscles:", "Work together", "Work opposite", "No effect", "None", "B", "Antagonists work opposite"),
        ("Pivot joint is:", "Atlas-axis", "Knee", "Hip", "None", "A", "Atlas-axis is pivot"),
        ("Hinge joint is:", "Knee", "Hip", "Shoulder", "None", "A", "Knee is hinge joint"),
        ("Ball and socket joint is:", "Knee", "Hip", "Elbow", "None", "B", "Hip is ball and socket"),
        ("Gliding joint is:", "Vertebrae", "Knee", "Hip", "None", "A", "Vertebrae gliding joint"),
        ("Sutures are in:", "Skull", "Vertebrae", "Limbs", "None", "A", "Sutures in skull"),
        ("Fontanelles are:", "Soft spots", "Joints", "Bones", "None", "A", "Fontanelles soft spots in infants"),
        ("Bone is composed of:", "Organic matrix", "Inorganic salts", "Both", "None", "C", "Bone has organic and inorganic"),
        ("Osteoblasts form:", "Bone", "Cartilage", "Marrow", "None", "A", "Osteoblasts form bone"),
        ("Osteoclasts resorb:", "Bone", "Cartilage", "Marrow", "None", "A", "Osteoclasts resorb bone"),
        ("Synovial fluid is secreted by:", "Synovial membrane", "Cartilage", "Bone", "None", "A", "Synovial membrane secretes"),
    ],
    "Neural Control and Coordination": [
        ("Neuron was discovered by:", "Waldeyer", "Golgi", "Cajal", "None", "A", "Waldeyer discovered neuron"),
        ("Neuron is structural unit of:", "Nervous system", "Circulatory system", "Respiratory system", "None", "A", "Neuron is nervous unit"),
        ("Neuron is functional unit of:", "Brain", "Nervous system", "Spinal cord", "None", "B", "Neuron functional in NS"),
        ("Neuron has:", "Cell body", "Dendrites", "Axon", "All", "D", "Neuron has all parts"),
        ("Myelin sheath is formed by:", "Axons", "Schwann cells", "Oligodendrocytes", "Both B and C", "D", "Myelin by Schwann and oligodendrocytes"),
        ("Node of Ranvier is:", "Myelinated", "Unmyelinated", "Both", "None", "B", "Node of Ranvier unmyelinated"),
        ("Saltatory conduction is in:", "Unmyelinated fibers", "Myelinated fibers", "Both", "None", "B", "Saltatory in myelinated"),
        ("Resting membrane potential is:", "-70 mV", "-90 mV", "+70 mV", "None", "A", "Resting potential -70mV"),
        ("Depolarization is:", "Inside becomes positive", "Outside becomes positive", "No change", "None", "A", "Inside becomes positive"),
        ("Action potential is:", "-70 to +30 mV", "-70 to -90 mV", "-90 to +30 mV", "None", "A", "Action potential -70 to +30mV"),
        ("Refractory period is:", "Absolute", "Relative", "Both", "None", "C", "Both absolute and relative"),
        ("Synapse was discovered by:", "Sherrington", "Golgi", "Cajal", "None", "A", "Sherrington discovered synapse"),
        ("Neurotransmitter at NMJ is:", "ACh", "Adrenaline", "Dopamine", "None", "A", "ACh at neuromuscular junction"),
        ("Excitatory postsynaptic potential is:", "Depolarization", "Hyperpolarization", "No change", "None", "A", "EPSP is depolarization"),
        ("Inhibitory postsynaptic potential is:", "Depolarization", "Hyperpolarization", "No change", "None", "B", "IPSP is hyperpolarization"),
        ("Summation can be:", "Spatial", "Temporal", "Both", "None", "C", "Both spatial and temporal"),
        ("Reflex arc has:", "Receptor", "Effector", "Sensory neuron", "All", "D", "Reflex arc has all"),
        ("Monosynaptic reflex is:", "Stretch reflex", "Withdrawal reflex", "Flexor reflex", "None", "A", "Stretch reflex monosynaptic"),
        ("Cornea is supplied by:", "V nerve", "VII nerve", "IX nerve", "X nerve", "A", "Cornea by trigeminal/V nerve"),
        ("Taste buds are in:", "Tongue", "Soft palate", "Epiglottis", "All", "D", "Taste buds multiple locations"),
        ("Olfactory receptor neurons are:", "Bipolar", "Multipolar", "Unipolar", "None", "A", "Olfactory neurons bipolar"),
        ("Photoreceptors are in:", "Retina", "Cornea", "Lens", "None", "A", "Photoreceptors in retina"),
        ("Rods are for:", "Bright light", "Dim light", "Color", "None", "B", "Rods for dim light"),
        ("Cones are for:", "Bright light", "Dim light", "No light", "None", "A", "Cones for bright light/color"),
        ("Auditory canal transmits:", "Sound waves", "Light waves", "Heat", "None", "A", "Auditory canal sound"),
        ("Organ of Corti is for:", "Hearing", "Balance", "Both", "None", "A", "Organ of Corti hearing"),
        ("Semicircular canals are for:", "Hearing", "Balance", "Vision", "None", "B", "Semicircular canals balance"),
        ("Cerebrospinal fluid is in:", "Subarachnoid space", "Ventricles", "Both", "None", "C", "CSF in subarachnoid and ventricles"),
        ("Blood-brain barrier is formed by:", "Endothelial cells", "Astrocytes", "Both", "None", "C", "BBB by endothelial and astrocytes"),
        ("Neuroglia are:", "Neurons", "Supporting cells", "Gland cells", "None", "B", "Neuroglia supporting cells"),
    ],
    "Chemical Coordination and Integration": [
        ("Endocrine glands are:", "Ductless", "With ducts", "Both", "None", "A", "Endocrine are ductless"),
        ("Hormones are:", "Chemical messengers", "Electrical messengers", "Both", "None", "A", "Hormones chemical messengers"),
        ("First hormone discovered was:", "Adrenaline", "Insulin", "Thyroxine", "None", "B", "Insulin first hormone"),
        ("Hormones act via:", "Receptors", "Channels", "Carriers", "All", "D", "Hormones use multiple pathways"),
        ("Second messenger is:", "cAMP", "ATP", "GTP", "None", "A", "cAMP is second messenger"),
        ("G protein is associated with:", "Cell membrane", "Nucleus", "Mitochondria", "None", "A", "G protein cell membrane"),
        ("Steroid hormones act on:", "Cell membrane", "Nucleus", "Cytoplasm", "None", "B", "Steroid hormones nuclear"),
        ("Peptide hormones act on:", "Cell membrane", "Nucleus", "Cytoplasm", "None", "A", "Peptide hormones membrane"),
        ("Hypothalamus is:", "Endocrine", "Exocrine", "Both", "None", "A", "Hypothalamus endocrine"),
        ("Pituitary is:", "Master gland", "Slave gland", "Both", "None", "A", "Pituitary master gland"),
        ("GH deficiency causes:", "Dwarfism", "Gigantism", "Acromegaly", "None", "A", "GH deficiency dwarfism"),
        ("TSH is secreted by:", "Anterior pituitary", "Posterior pituitary", "Intermediate lobe", "None", "A", "TSH anterior pituitary"),
        ("ACTH is secreted by:", "Anterior pituitary", "Posterior pituitary", "Intermediate lobe", "None", "A", "ACTH anterior pituitary"),
        ("ADH is secreted by:", "Anterior pituitary", "Posterior pituitary", "Intermediate lobe", "None", "B", "ADH posterior pituitary"),
        ("Oxytocin is secreted by:", "Anterior pituitary", "Posterior pituitary", "Intermediate lobe", "None", "B", "Oxytocin posterior pituitary"),
        ("Thyroid hormones include:", "T3", "T4", "Both", "None", "C", "Thyroid T3 and T4"),
        ("Calcitonin is from:", "Thyroid", "Parathyroid", "C cells", "None", "C", "Calcitonin from C cells"),
        ("PTH is from:", "Thyroid", "Parathyroid", "C cells", "None", "B", "PTH from parathyroid"),
        ("Insulin is from:", "Alpha cells", "Beta cells", "Delta cells", "None", "B", "Insulin from beta cells"),
        ("Glucagon is from:", "Alpha cells", "Beta cells", "Delta cells", "None", "A", "Glucagon from alpha cells"),
        ("Somatostatin is from:", "Alpha cells", "Beta cells", "Delta cells", "None", "C", "Somatostatin from delta cells"),
        ("Epinephrine is from:", "Adrenal cortex", "Adrenal medulla", "Kidney", "None", "B", "Epinephrine adrenal medulla"),
        ("Cortisol is from:", "Adrenal cortex", "Adrenal medulla", "Kidney", "None", "A", "Cortisol adrenal cortex"),
        ("Aldosterone is from:", "Adrenal cortex", "Adrenal medulla", "Kidney", "None", "A", "Aldosterone adrenal cortex"),
        ("Testosterone is from:", "Testes", "Ovaries", "Adrenal", "None", "A", "Testosterone from testes"),
        ("Estrogen is from:", "Testes", "Ovaries", "Adrenal", "None", "B", "Estrogen from ovaries"),
        ("Progesterone is from:", "Testes", "Ovaries", "Adrenal", "All", "D", "Progesterone from all"),
        ("Melatonin is from:", "Pineal", "Hypothalamus", "Pituitary", "None", "A", "Melatonin from pineal"),
        ("Leptin is from:", "Fat tissue", "Stomach", "Intestine", "None", "A", "Leptin from fat"),
    ],
}

total = 0
for chapter_name, pyqs in chapters_pyqs.items():
    try:
        c = Chapter.objects.get(subject=s, name=chapter_name)
        MCQQuestion.objects.filter(chapter=c).delete()
        for order, q in enumerate(pyqs):
            MCQQuestion.objects.create(
                chapter=c,
                question_text=q[0],
                option_a=q[1],
                option_b=q[2],
                option_c=q[3],
                option_d=q[4],
                correct_option=q[5],
                explanation=q[6],
                order=order
            )
        print(f"Added {len(pyqs)} PYQs to {chapter_name}")
        total += len(pyqs)
    except Chapter.DoesNotExist:
        print(f"Chapter {chapter_name} not found")
    except Exception as e:
        print(f"Error with {chapter_name}: {e}")

print(f"\nTotal added: {total} PYQs")