import os
import sys
import django

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'vidyahub.settings')
django.setup()

from main.models import Grade, Chapter, MCQQuestion

print("=" * 60)
print("Generating Unique MCQs for Class 11 Chapters (10 per chapter)")
print("=" * 60)

grade = Grade.objects.get(slug='class-11')
chapters = list(Chapter.objects.filter(subject__grade=grade))

chapter_questions = {
    "Physical World": [
        ("Physics deals with:", "Study of matter and energy", "Only matter", "Only energy", "Living things", "A", "Physics = matter and energy"),
        ("Scientific method involves:", "Observation, hypothesis, experiment", "Only experiments", "Only theories", "Nothing", "A", "Systematic approach"),
        ("Physics is:", "Fundamental science", "Applied only", "Secondary", "Not important", "A", "Base for other sciences"),
        ("Branches include:", "Mechanics, thermodynamics, quantum", "Only mechanics", "Only chemistry", "Nothing", "A", "Multiple branches"),
        ("Contribution of physicists helps:", "Technology development", "Nothing", "Just knowledge", "Entertainment", "A", "Tech advancement"),
        ("Physics equations describe:", "Natural phenomena", "Only numbers", "Nothing", "Myths", "A", "Nature mathematically"),
        ("Measurement in physics requires:", "Standard units", "Random units", "Only numbers", "Nothing", "A", "Standardization"),
        ("laws of physics are:", "Universal", "Local only", "Changeable", "Nothing", "A", "Apply everywhere"),
        ("Experimental physics involves:", "Hands-on investigation", "Only reading", "Memorizing", "Nothing", "A", "Practical work"),
        ("Theoretical physics involves:", "Mathematical modeling", "Only experiments", "Nothing", "Observations only", "A", "Theory development"),
    ],
    "Units and Measurement": [
        ("SI units are:", "Internationally accepted", "Locally used", "Only scientific", "Traditional", "A", "International standard"),
        ("Fundamental quantities are:", "Independent of each other", "Dependent", "Related", "Nothing", "A", "Base quantities"),
        ("Measurement errors can be:", "Random or systematic", "Positive only", "Negative only", "No error", "A", "Various sources"),
        ("Significant figures indicate:", "Precision of measurement", "Exact value", "Approximation", "Nothing", "A", "Precision tracking"),
        ("Dimensional analysis helps:", "Check equation correctness", "Make calculations", "Nothing", "Find values", "A", "Validation tool"),
        ("Least count of instrument determines:", "Smallest measurable value", "Largest value", "Precision", "Nothing", "A", "Measurement resolution"),
        ("vernier caliper measures:", "Small lengths accurately", "Large distances", "Angles", "Nothing", "A", "Small length precision"),
        ("Screw gauge measures:", "Very small thicknesses", "Large distances", "Weights", "Nothing", "A", "Thickness measurement"),
        ("Parallax error occurs when:", "Eye not perpendicular to scale", "Eye at any position", "Reading correctly", "Nothing", "A", "Viewing position error"),
        ("Precision and accuracy are:", "Different concepts", "Same", "Related inversely", "Nothing", "A", "Precision vs accuracy"),
    ],
    "Motion in a Straight Line": [
        ("Position describes:", "Location of particle", "Movement", "Speed", "Nothing", "A", "Point in space"),
        ("Displacement is:", "Shortest distance in direction", "Total path length", "Speed", "Nothing", "A", "Vector quantity"),
        ("Average velocity equals:", "Displacement divided by time", "Distance divided by time", "Speed", "Nothing", "A", "Displacement/time"),
        ("Instantaneous velocity is:", "Velocity at specific instant", "Average velocity", "Constant velocity", "Nothing", "A", "At particular time"),
        ("Acceleration is rate of change of:", "Velocity", "Position", "Speed", "Nothing", "A", "Velocity change"),
        ("Equations of motion apply to:", "Constant acceleration", "Variable acceleration", "Any motion", "Nothing", "A", "Uniform acceleration"),
        ("Free fall motion has:", "Constant acceleration g", "Variable acceleration", "No acceleration", "Decreasing acceleration", "A", "Gravity only"),
        ("Relative motion depends on:", "Reference frame", "Absolute position", "Constant speed", "Nothing", "A", "Frame of reference"),
        ("Graph of position vs time gives:", "Velocity", "Acceleration", "Displacement", "Nothing", "A", "Slope = velocity"),
        ("Area under velocity-time graph gives:", "Displacement", "Acceleration", "Distance", "Nothing", "A", "Integration gives displacement"),
    ],
    "Motion in a Plane": [
        ("Position in plane uses:", "Two coordinates", "One coordinate", "Three coordinates", "Nothing", "A", "2D location"),
        ("Vector addition uses:", "Triangle or parallelogram law", "Simple addition", "Multiplication", "Nothing", "A", "Geometric addition"),
        ("Zero vector indicates:", "No magnitude and direction", "Large magnitude", "Small magnitude", "Nothing", "A", "Null vector"),
        ("Scalar has:", "Only magnitude", "Only direction", "Both", "Nothing", "A", "Magnitude only"),
        ("Vector has:", "Both magnitude and direction", "Only magnitude", "Only direction", "Nothing", "A", "Directional quantity"),
        ("Projectile motion has:", "Horizontal and vertical components", "Only horizontal", "Only vertical", "Constant", "A", "Two directions"),
        ("Circular motion involves:", "Continuous direction change", "Constant direction", "Straight path", "Nothing", "A", "Perpendicular force"),
        ("Centripetal force directs:", "Towards center", "Away from center", "Tangent", "Nothing", "A", "Towards center"),
        ("Angular displacement measures:", "Angle turned", "Distance moved", "Time", "Nothing", "A", "Angle in radians"),
        ("Uniform circular motion has:", "Constant speed", "Constant velocity", "Accelerating", "Decelerating", "A", "Speed constant"),
    ],
    "Laws of Motion": [
        ("Newton's first law describes:", "Inertia of objects", "Forces", "Acceleration", "Nothing", "A", "Property of matter"),
        ("Momentum equals:", "Mass × velocity", "Mass × acceleration", "Force × time", "Nothing", "A", "Linear momentum"),
        (" Newton's second law states:", "F = ma", "F = mv", "F = m/a", "Nothing", "A", "Force equals mass×acceleration"),
        ("Impulse equals:", "Change in momentum", "Force × time", "Acceleration", "Nothing", "A", "Force × time"),
        ("Newton's third law states:", "Action-reaction equal and opposite", "Force equals", "Acceleration equals", "Nothing", "A", "Action = reaction"),
        ("Conservation of momentum applies when:", "No external force", "External force present", "Any case", "Nothing", "A", "Isolated system"),
        ("Friction opposes:", "Relative motion", "Absolute motion", "Rest", "Nothing", "A", "Motion between surfaces"),
        ("Apparent weight changes in:", "Accelerating elevator", "Rest", "Constant velocity", "Nothing", "A", "Non-inertial frame"),
        ("Circular turning uses:", "Centripetal force", "Tangential force", "External force", "Nothing", "A", "Towards center"),
        ("Banking of road provides:", "Centripetal force", "Normal force", "Friction", "Nothing", "A", "Curve safety"),
    ],
    "Work, Energy and Power": [
        ("Work equals:", "Force × displacement", "Force × time", "Mass × acceleration", "Nothing", "A", "Dot product F·s"),
        ("Kinetic energy equals:", "½mv²", "mv²", "mgh", "Nothing", "A", "Motion energy"),
        ("Potential energy equals:", "mgh", "½mv²", "Force × distance", "Nothing", "A", "Position energy"),
        ("Work-energy theorem states:", "Work done = change in KE", "Constant KE", "No relation", "Nothing", "A", "Energy transfer"),
        ("Power equals:", "Work/time", "Energy × time", "Force × velocity", "Nothing", "A", "Rate of doing work"),
        ("Conservation of energy applies when:", "Only conservative forces", "Any forces", "No forces", "Nothing", "A", "System isolated"),
        ("Potential energy of spring equals:", "½kx²", "kx²", "kx", "Nothing", "A", "Hooke's law energy"),
        ("Collision types include:", "Elastic and inelastic", "Only elastic", "Only inelastic", "No types", "A", "Energy conserved or not"),
        ("Potential energy in gravitational field equals:", "mgh", "GMm/r", "GMm/r²", "Nothing", "A", "Near Earth surface"),
        ("Energy sources include:", "Renewable and non-renewable", "Only one type", "No source", "Nothing", "A", "Various forms"),
    ],
    "System of Particles and Rotational Motion": [
        ("Center of mass is:", "Point where mass appears concentrated", "Heaviest point", "Lightest point", "Nothing", "A", "Mass distribution center"),
        ("Torque equals:", "Force × perpendicular distance", "Force", "Mass", "Nothing", "A", "Rotational force"),
        ("Moment of inertia depends on:", "Mass distribution", "Total mass", "Shape only", "Nothing", "A", "About axis"),
        ("Angular momentum equals:", "I × ω", "m × v", "Force", "Nothing", "A", "Rotational momentum"),
        ("Conservation of angular momentum applies when:", "No external torque", "External torque", "Any case", "Nothing", "A", "Isolated system"),
        ("Rotational kinetic energy equals:", "½Iω²", "Iω²", "I²ω", "Nothing", "A", "Angular motion energy"),
        ("Parallel axis theorem relates:", "Different parallel axes", "Same axis only", "No relation", "Nothing", "A", "Axis calculation"),
        ("Perpendicular axis theorem is for:", "Planar bodies", "3D bodies", "Only spheres", "Nothing", "A", "2D objects"),
        ("Radius of gyration relates to:", "Moment of inertia", "Mass", "Distance", "Nothing", "A", "Distribution measure"),
        ("Pure rolling involves:", "Rotational plus translational", "Only rotational", "Only translational", "Nothing", "A", "Combined motion"),
    ],
    "Gravitation": [
        ("Universal law of gravitation: F =", "GMm/r²", "GMm/r", "GM/r²", "Nothing", "A", "Inverse square law"),
        ("Gravitational constant G is:", "Universal constant", "Variable", "Depends on mass", "Nothing", "A", "Same everywhere"),
        ("Acceleration due to gravity g is:", "9.8 m/s²", "Variable everywhere", "Constant", "Nothing", "A", "Varies slightly"),
        ("Acceleration due to gravity varies with:", "Altitude and latitude", "Mass only", "Shape only", "Nothing", "A", "Position dependent"),
        ("Gravitational potential equals:", "-GMm/r", "GMm/r", "GM/r", "Nothing", "A", "Energy per unit mass"),
        ("Weightlessness occurs when:", "Free fall", "At rest", "Moving", "Nothing", "A", "No normal force"),
        ("Orbital speed depends on:", "Distance from center", "Mass only", "Radius only", "Nothing", "A", "Orbital mechanics"),
        ("Escape velocity equals:", "√2 × orbital velocity", "Orbital velocity", "Half orbital", "Nothing", "A", "Orbit relationship"),
        ("Satellite motion involves:", "Circular path", "Elliptical path", "Straight line", "Nothing", "A", "Closed path"),
        ("Geostationary satellite:", "Fixed position relative to Earth", "Moving fast", "Low altitude", "Nothing", "A", "Synchronous orbit"),
    ],
    "Mechanical Properties of Solids": [
        ("Stress equals:", "Force/Area", "Only force", "Only area", "Nothing", "A", "Force per area"),
        ("Strain equals:", "Change in dimension/original", "Force", "Area", "Nothing", "A", "Relative deformation"),
        ("Young's modulus relates:", "Stress/Strain", "Stress × Strain", "Inverse strain", "Nothing", "A", "Elastic property"),
        ("Hooke's law states:", "Stress ∝ strain", "Stress independent", "No relation", "Anything", "A", "Linear region"),
        ("Elastic potential energy equals:", "½ × stress × strain × volume", "Stress × volume", "Strain × volume", "Nothing", "A", "Energy stored"),
        ("Poisson's ratio is:", "Lateral strain/Longitudinal strain", "Inverse", "One type only", "Nothing", "A", "Shape change measure"),
        ("Shear modulus relates:", "Shear stress/shear strain", "Volume change", "No relation", "Nothing", "A", "Shearing deformation"),
        ("Bulk modulus relates:", "Volume stress/volume strain", "Linear", "Shear", "Nothing", "A", "Volume elasticity"),
        ("Ductile materials can be:", "Drawn into wires", "Broken easily", "No use", "Nothing", "A", "Deformation ability"),
        ("Brittle materials break:", "Without significant deformation", "Easily shaped", "Stretch", "Nothing", "A", "Low ductility"),
    ],
    "Mechanical Properties of Fluids": [
        ("Pressure equals:", "Force/Area", "Force", "Mass", "Nothing", "A", "Force per area"),
        ("Buoyant force equals:", "Weight of displaced fluid", "Volume", "Density", "Nothing", "A", "Archimedes principle"),
        ("Archimedes principle applies to:", "Floating and submerged bodies", "Only solids", "Only liquids", "Gases only", "A", "Buoyancy"),
        ("Pascal's law states:", "Pressure transmitted equally", "Pressure varies", "No relation", "Anything", "A", "Transmission"),
        ("Surface tension is:", "Force/Length", "Force/Area", "Energy/Area", "Nothing", "A", "Line tension"),
        ("Viscosity opposes:", "Relative motion between layers", "Motion", "Rest", "Nothing", "A", "Fluid friction"),
        ("Reynolds number indicates:", "Laminar or turbulent", "Speed only", "Density only", "Nothing", "A", "Flow type"),
        ("Bernoulli's equation relates:", "Pressure, velocity, height", "Only pressure", "Only velocity", "Nothing", "A", "Energy conservation"),
        ("Continuity equation states:", "A₁v₁ = A₂v₂", "Pressure constant", "No relation", "Anything", "A", "Mass conservation"),
        ("Capillary rise depends on:", "Surface tension, contact angle", "Only tension", "Only area", "Nothing", "A", "Tube radius"),
    ],
    "Oscillations": [
        ("Simple harmonic motion is:", "Periodic with sinusoidal variation", "Random", "Non-periodic", "Nothing", "A", "Sinusoidal oscillation"),
        ("Time period is:", "Time for one oscillation", "Frequency", "Amplitude", "Nothing", "A", "One complete cycle"),
        ("Frequency is:", "1/Time period", "Time period", "Amplitude squared", "Nothing", "A", "Cycles per second"),
        ("Maximum displacement is:", "Amplitude", "Period", "Frequency", "Nothing", "A", "Maximum from mean"),
        ("Simple pendulum time period equals:", "2π√(l/g)", "2πl/g", "√(g/l)", "Nothing", "A", "Simple pendulum formula"),
        ("Energy in SHM alternates between:", "Kinetic and potential", "Constant", "No energy", "Zero average", "A", "Energy exchange"),
        ("Damped oscillations:", "Amplitude decreases with time", "Constant", "Increases", "Nothing", "A", "Energy loss"),
        ("Driven oscillations occur with:", "External periodic force", "No force", "Constant force", "Nothing", "A", "Forced vibration"),
        ("Resonance occurs when:", "Driving frequency equals natural frequency", "Different frequencies", "No relation", "Anything", "A", "Maximum amplitude"),
        ("SHM can be represented as:", "Sine or cosine wave", "Linear", "Parabolic", "Nothing", "A", "Waveform"),
    ],
    "Waves": [
        ("Waves transfer:", "Energy without matter", "Matter only", "Both matter and energy", "Nothing", "A", "Energy propagation"),
        ("Mechanical waves need:", "Medium", "No medium", "Vacuum", "Nothing", "A", "Material medium"),
        ("Sound waves are:", "Longitudinal", "Transverse", "Both", "Nothing", "A", "Compressional"),
        ("Electromagnetic waves are:", "Transverse", "Longitudinal", "Both", "No type", "A", "No medium needed"),
        ("Frequency of wave equals:", "1/Wavelength", "Wavelength", "Amplitude", "Nothing", "A", "Wave property"),
        ("Doppler effect relates to:", "Moving source/observer", "Stationary only", "No relation", "Anything", "A", "Frequency change"),
        ("Beats occur from:", "Superposition of slightly different frequencies", "Single frequency", "No beats", "Nothing", "A", "Interference"),
        ("Standing waves have:", "Nodes and antinodes", "No special points", "Only nodes", "Nothing", "A", "Fixed pattern"),
        ("Resonance in tubes occurs at:", "Specific wavelengths", "Any wavelength", "No resonance", "Nothing", "A", "Harmonics"),
        ("Intensity of wave relates to:", "Square of amplitude", "Amplitude", "Frequency", "Nothing", "A", "Energy flux"),
    ],
    "Thermodynamics": [
        ("Heat is:", "Energy transfer due to temperature difference", "Internal energy", "Temperature", "Work", "A", "Energy flow"),
        ("Internal energy includes:", "Kinetic and potential of molecules", "Only kinetic", "Only potential", "Nothing", "A", "Molecular Energy"),
        ("First law of thermodynamics: ΔU =", "Q - W", "Q + W", "W - Q", "Nothing", "A", "Energy conservation"),
        ("Isothermal process has:", "Constant temperature", "Constant pressure", "Constant volume", "Nothing", "A", "Temperature constant"),
        ("Adiabatic process has:", "No heat exchange", "Heat exchange", "Constant heat", "Nothing", "A", "No heat transfer"),
        ("Carnot cycle is for:", "Maximum efficiency", "Minimum efficiency", "No efficiency", "Anything", "A", "Ideal engine"),
        ("Second law indicates:", "Irreversibility", "Reversibility", "No direction", "Anything", "A", "Direction of processes"),
        ("Entropy measures:", "Disorder", "Order", "Energy", "Nothing", "A", "Randomness"),
        ("Heat engines convert:", "Heat to work", "Work to heat", "No conversion", "Anything", "A", "Energy conversion"),
        ("Refrigerators transfer:", "Heat from cold to hot", "Hot to cold", "No transfer", "Anything", "A", "Against gradient"),
    ],
    "Kinetic Theory": [
        ("Kinetic theory explains:", "Behavior of gases", "Solids only", "Liquids only", "Nothing", "A", "Gas molecular motion"),
        ("Pressure of gas is due to:", "Molecular collisions", "Weight", "Gravity", "Nothing", "A", "Momentum transfer"),
        ("Average kinetic energy relates to:", "Temperature", "Volume", "Pressure", "Nothing", "A", "Temperature measure"),
        ("Ideal gas follows:", "PV = nRT", "PV = constant", "P = V", "Nothing", "A", "Equation of state"),
        ("Real gases deviate from ideal at:", "High pressure, low temperature", "Low pressure", "High temperature", "Nothing", "A", "Intermolecular forces"),
        ("Root mean square speed equals:", "√(3RT/M)", "RT/M", "√(RT/M)", "Nothing", "A", "Average speed"),
        ("Degrees of freedom determine:", "Independent motions", "Number of atoms", "Pressure", "Nothing", "A", "Motion possibilities"),
        ("Law of equipartition allocates:", "Energy equally among degrees", "Unequally", "No relation", "Anything", "A", "Energy distribution"),
        ("Specific heat capacities depend on:", "Degrees of freedom", "Mass only", "Volume only", "Nothing", "A", "Molecular structure"),
        ("Mean free path is:", "Average distance between collisions", "Path length", "Time", "Nothing", "A", "Collision distance"),
    ],
    "Oscillations": [
        ("Periodic motion repeats:", "At regular intervals", "Irregularly", "Once", "Nothing", "A", "Regular repetition"),
        ("SHM equation: x = A sin(ωt + φ), where ω is:", "Angular frequency", "Amplitude", "Phase", "Nothing", "A", "Angular velocity"),
        ("Time period T =", "2π/ω", "ω/2π", "1/ω", "Nothing", "A", "Inverse relationship"),
        ("Simple pendulum is:", "Simple harmonic for small angles", "SHM for all angles", "Not SHM", "Anything", "A", "Small angle approximation"),
        ("Damped oscillation equation: x = Ae^(-bt)cos(ω't + φ), b is:", "Damping constant", "Amplitude", "Frequency", "Nothing", "A", "Decay constant"),
        ("Forced oscillation: x = A sin(ωt) + B sin(ωt)", "Resonance", "No resonance", "One frequency", "Nothing", "A", "At ω = ω₀ resonance"),
        ("Combination of two SHMs gives:", "Lissajous figures", "Straight line", "Circle", "Nothing", "A", "Two perpendicular SHMs"),
        ("Fourier theorem states:", "Any periodic as sum of sinusoids", "Not applicable", "No sum required", "Anything", "A", "Wave composition"),
        ("Beat frequency equals:", "|f₁ - f₂|", "f₁ + f₂", "f₁ × f₂", "Nothing", "A", "Difference frequency"),
        ("Standing wave has nodes at:", "Fixed positions", "Moving positions", "No nodes", "Anything", "A", "Points of no motion"),
    ],
    "Waves": [
        ("Progressive wave transfers:", "Energy in medium", "Matter", "Both", "Nothing", "A", "Energy propagation"),
        ("Transverse wave oscillation is:", "Perpendicular to propagation", "Along propagation", "Any direction", "Nothing", "A", "Perpendicular"),
        ("Longitudinal wave has:", "Compressions and rarefactions", "Crests and troughs", "No pattern", "Anything", "A", "Density variation"),
        ("Wave equation: y = A sin(kx - ωt), k =", "2π/λ", "λ/2π", "1/λ", "Nothing", "A", "Wave number"),
        ("Doppler effect for sound: frequency changes with:", "Moving source or observer", "Stationary only", "No change", "Anything", "A", "Motion effect"),
        ("Beats occur from:", "Interference of close frequencies", "Single frequency", "No beats", "Anything", "A", "Superposition"),
        ("Stationary wave equation: y = A sin(kx)cos(ωt)", "Nodes at sin(kx)=0", "No nodes", "Moving nodes", "Anything", "A", "Fixed nodes"),
        ("Resonance occurs at:", "L = nλ/4 for open organ pipe", "Any length", "No resonance", "Anything", "A", "Harmonic condition"),
        ("Intensity ∝", "Amplitude²", "Amplitude", "Frequency", "Nothing", "A", "Energy proportional"),
        ("Speed of sound in air:", "331 m/s at STP", "Depends on humidity", "Independent", "Anything", "A", "Air properties"),
    ],
    "The Living World": [
        ("Living organisms show:", "Metabolism, growth, reproduction", "Only movement", "One feature", "Nothing", "A", "Life characteristics"),
        ("Binomial nomenclature gives:", "Genus and species names", "Common name", "Phylum only", "Nothing", "A", "Two-part name"),
        ("Classification is based on:", "Evolutionary relationships", "Similarities only", "One character", "Anything", "A", "Phylogeny"),
        ("Biodiversity includes:", "Millions of species", "Few species", "No diversity", "Anything", "A", "Species variety"),
        ("Domains are:", "Archaea, Bacteria, Eukarya", "Two kingdoms", "Five kingdoms", "Anything", "A", "Three domains"),
        ("Growth in living things is due to:", "Cell division", "Cell expansion", "No change", "Anything", "A", "Mitosis"),
        ("Reproduction is essential for:", "Continuity of species", "Individual life", "Health", "Anything", "A", "Species survival"),
        ("Variations help in:", "Adaptation and evolution", "No change", "One form", "Anything", "A", "Survival"),
        ("Plants are:", "Autotrophs", "Heterotrophs", "Only saprophytes", "Anything", "A", "Self-feeders"),
        ("Animals are:", "Heterotrophs", "Autotrophs", "Only parasites", "Anything", "A", "Other feeders"),
    ],
    "Animal Kingdom": [
        ("Animal classification is based on:", "Body plan, symmetry, coelom", "Size only", "One feature", "Anything", "A", "Multiple features"),
        ("Porifera have:", "Pores and spicules", "Notochord", "Vertebrae", "Anything", "A", "Pore-bearing"),
        ("Coelomates have:", "True coelom", "No coelom", "Pseudocoelom", "Anything", "A", "Body cavity"),
        ("Arthropods have:", "Jointed appendages", "Notochord", "Sponges", "Anything", "A", "Jointed legs"),
        ("Mollusks have:", "Soft body, shell", "Notochord", "Backbone", "Anything", "A", "Soft-bodied"),
        ("Echinoderms are:", "Spiny-skinned, radial symmetry", "Bilateral", "No symmetry", "Anything", "A", "Spiny skin"),
        ("Chordates have:", "Notochord at some stage", "No notochord", "Shell", "Anything", "A", "Dorsal nerve"),
        ("Vertebrates are:", "With backbone", "Without backbone", "Invertebrates", "Anything", "A", "Backbone"),
        ("Cold-blooded animals have:", "Variable body temperature", "Constant", "No temperature", "Anything", "A", "Ectothermic"),
        ("Warm-blooded animals maintain:", "Constant body temperature", "Variable", "No regulation", "Anything", "A", "Endothermic"),
    ],
    "Structural Organisation in Animals": [
        ("Tissues are:", "Groups of similar cells", "Single cells", "Random collection", "Anything", "A", "Cell groups"),
        ("Epithelial tissue covers:", "Body surfaces", "Inside organs", "Blood", "Anything", "A", "Surface covering"),
        ("Connective tissue includes:", "Blood, bone, cartilage", "Nerve tissue", "Muscle", "Anything", "A", "Various types"),
        ("Muscle tissue has:", "Contractile proteins", "Nerve cells", "Epithelium", "Anything", "A", "Contraction"),
        ("Nerve tissue transmits:", "Electrical impulses", "Chemicals only", "Messages", "Anything", "A", "Signals"),
        ("Organs are made of:", "Different tissues", "Same tissue", "One tissue only", "Anything", "A", "Tissue combination"),
        ("Organ systems are:", "Groups of organs", "Single organ", "Tissues only", "Anything", "A", "Functional units"),
        ("Homeostasis maintains:", "Internal balance", "External environment", "Nothing", "Anything", "A", "Internal steady state"),
        ("Negative feedback regulates:", "Physiological variables", "Increases changes", "No regulation", "Anything", "A", "Control mechanism"),
        ("Endocrine system uses:", "Hormones", "Nerves only", "Enzymes", "Anything", "A", "Chemical messengers"),
    ],
    "Biomolecules": [
        ("Carbohydrates are:", "Carbon, hydrogen, oxygen with H:O = 2:1", "Proteins", "Lipids", "Anything", "A", "CH₂O ratio"),
        ("Glucose is:", "Monosaccharide", "Disaccharide", "Polysaccharide", "Anything", "A", "Simple sugar"),
        ("Starch is:", "Polysaccharide", "Disaccharide", "Monosaccharide", "Anything", "A", "Polymer"),
        ("Proteins are polymers of:", "Amino acids", "Fatty acids", "Nucleotides", "Anything", "A", "Amino acid chain"),
        ("Amino acids join by:", "Peptide bonds", "Glycosidic bonds", "Ester bonds", "Anything", "A", "Bond type"),
        ("Lipids are hydrophobic due to:", "Nonpolar groups", "Polar groups", "Charges", "Anything", "A", "Water-fearing"),
        ("Nucleic acids are polymers of:", "Nucleotides", "Amino acids", "Sugars", "Anything", "A", "Genetic material"),
        ("DNA has:", "Double helix structure", "Single strand", "Triple helix", "Anything", "A", "Helical form"),
        ("RNA is usually:", "Single-stranded", "Double helix", "Triple", "Anything", "A", "Single strand"),
        ("Enzymes are:", "Biological catalysts", "Inhibitors", "Substrates", "Anything", "A", "Bio catalysts"),
    ],
    "Cell: The Unit of Life": [
        ("Cell is:", "Basic structural and functional unit", "Tissue", "Organ", "Nothing", "A", "Life unit"),
        ("Cell theory states:", "All organisms are made of cells", "One-celled only", "No theory", "Anything", "A", "Cellular basis"),
        ("Prokaryotic cells lack:", "Membrane-bound nucleus", "DNA", "Ribosomes", "Anything", "A", "True nucleus"),
        ("Eukaryotic cells have:", "Membrane-bound nucleus", "Naked DNA", "No organelles", "Anything", "A", "Membrane organelles"),
        ("Mitochondria are:", "Powerhouse of cell", "Protein synthesis", "Cell division", "Anything", "A", "ATP production"),
        ("Ribosomes are for:", "Protein synthesis", "Energy production", "Division", "Anything", "A", "Translation"),
        ("Endoplasmic reticulum is for:", "Transport and synthesis", "Energy", "Division", "Anything", "A", "Intracellular path"),
        ("Golgi apparatus modifies:", "Proteins and lipids", "DNA", "RNA", "Anything", "A", "Processing"),
        ("Lysosomes contain:", "Digestive enzymes", "ATP", "DNA", "Anything", "A", "Enzymes"),
        ("Cell membrane is:", "Selectively permeable", "Impermeable", "Anything", "Anything", "A", "Selective transport"),
    ],
    "Cell Cycle and Cell Division": [
        ("Cell cycle has:", "Interphase and M phase", "Only division", "Only growth", "Anything", "A", "Two phases"),
        ("Interphase includes:", "G1, S, G2 phases", "M phase only", "Prophase only", "Anything", "A", "Preparation"),
        ("S phase is for:", "DNA replication", "Protein synthesis", "Growth", "Anything", "A", "Synthesis"),
        ("M phase includes:", "Mitosis and cytokinesis", "Only interphase", "Growth", "Anything", "A", "Division"),
        ("Prophase shows:", "Chromatin condensation", "Chromatid separation", "Nothing", "Anything", "A", "Condensation"),
        ("Metaphase shows:", "Chromosomes at equator", "Nuclear envelope intact", "Nothing", "Anything", "A", "Alignment"),
        ("Anaphase shows:", "Sister chromatids separate", "Condensation", "Nothing", "Anything", "A", "Separation"),
        ("Telophase shows:", "Nucleus reformation", "Chromosome division", "Nothing", "Anything", "A", "Reformation"),
        ("Cytokinesis divides:", "Cytoplasm", "Nucleus only", "Nothing", "Anything", "A", "Cell division"),
        ("Cancer involves:", "Uncontrolled cell division", "No division", "Controlled", "Anything", "A", "Abnormal growth"),
    ],
    "Transport in Plants": [
        ("Xylem transports:", "Water and minerals", "Food", "Organic compounds", "Anything", "A", "Upward transport"),
        ("Phloem transports:", "Organic solutes", "Water", "Minerals", "Anything", "A", "Bidirectional"),
        ("Root pressure drives:", "Water uptake", "Transpiration", "Nothing", "Anything", "A", "Pressure flow"),
        ("Transpiration pull is due to:", "Water loss from leaves", "Water uptake", "Nothing", "Anything", "A", "Evaporation"),
        ("Cohesion is:", "Water molecules attracted to each other", "To walls", "Nothing", "Anything", "A", "Mutual attraction"),
        ("Adhesion is:", "Water attracted to other substances", "Cohesion", "No relation", "Anything", "A", "To surfaces"),
        ("Capillary rise is due to:", "Adhesion and cohesion", "Gravity", "Transpiration", "Anything", "A", "Capillary action"),
        ("Stomata regulate:", "Gas exchange and water loss", "Water only", "CO₂ only", "Anything", "A", "Exchange"),
        ("Guttation is due to:", "Root pressure", "Transpiration pull", "Nothing", "Anything", "A", "Water exudation"),
        ("Phloem loading uses:", "Active transport", "Diffusion", "Passive", "Anything", "A", "Energy requiring"),
    ],
    "Mineral Nutrition": [
        ("Essential elements are:", "Required for plant growth", "All elements", "Many elements", "Anything", "A", "Growth needed"),
        ("Nitrogen is needed for:", "Leaf growth", "Root growth", "Flowering", "Anything", "A", "Vegetative"),
        ("Phosphorus is for:", "Root and flower development", "Leaf", "Stem", "Anything", "A", "Reproductive"),
        ("Potassium regulates:", "Stomatal activity", "Flowering", "Root growth", "Anything", "A", "Opening/closing"),
        ("Iron is part of:", "Chlorophyll synthesis", "Root development", "Flowering", "Anything", "A", "Pigment"),
        ("Micronutrients needed in:", "Small quantities", "Large quantities", "No requirement", "Anything", "A", "Trace amounts"),
        ("Nitrogen fixation is by:", "Bacteria", "Fungi", "Animals", "Anything", "A", "Biological N₂→NH₃"),
        ("Mycorrhiza helps:", "Nutrient absorption", "Photosynthesis", "Reproduction", "Anything", "A", "Symbiosis"),
        ("Hydroponics is:", "Soilless cultivation", "Soil cultivation", "Aeroponics", "Anything", "A", "Water culture"),
        ("Fertilizers provide:", "Essential nutrients", "Water", "Disease resistance", "Anything", "A", "Artificial feeding"),
    ],
    "Photosynthesis": [
        ("Photosynthesis converts:", "CO₂ + H₂O to carbohydrates", "Respiration", "Only CO₂", "Anything", "A", "Carbon fixation"),
        ("Light reactions occur in:", "Thylakoid membrane", "Stroma", "Cytoplasm", "Anything", "A", "Membrane"),
        ("Dark reactions occur in:", "Stroma", "Thylakoid", "Membrane", "Anything", "A", "Calvin cycle"),
        ("Chlorophyll absorbs:", "Blue and red light", "Green light", "All light", "Anything", "A", "Specific colors"),
        ("Primary acceptor of CO₂ is:", "RuBP", "Glucose", "ATP", "Anything", "A", "5-carbon compound"),
        ("Products of light reactions are:", "ATP and NADPH", "Oxygen", "CO₂", "Anything", "A", "Energy carriers"),
        ("C₃ pathway is:", "Calvin cycle", "C₄ pathway", "CAM", "Anything", "A", "Three-carbon"),
        ("C₄ plants:", "Have Kranz anatomy", "No special", "No difference", "Anything", "A", "Two layers"),
        ("Photorespiration:", "有害于植物", "Beneficial", "中性", "A", "Oxygen competing with CO₂"),
        ("Factors affecting photosynthesis:", "Light, CO₂, temperature", "Only light", "One factor", "Anything", "A", "Multiple factors"),
    ],
    "Respiration in Plants": [
        ("Respiration releases:", "Energy from substrates", "Water", "CO₂ only", "Anything", "A", "Energy from food"),
        ("Glycolysis occurs in:", "Cytoplasm", "Mitochondria", "Nucleus", "Anything", "A", "Cytosol"),
        ("Krebs cycle occurs in:", "Mitochondrial matrix", "Cytoplasm", "Membrane", "Anything", "A", "Inside organelle"),
        ("Electron transport yields:", "ATP", "NADH", "FADH₂", "Anything", "A", "Energy"),
        ("Anaerobic respiration produces:", "Ethanol or lactate", "More ATP", "Water", "Anything", "A", "Limited ATP"),
        ("R.Q. is:", "CO₂ released / O₂ consumed", "O₂/CO₂", "One value", "Anything", "A", "Ratio"),
        ("Carbohydrates have R.Q. =", "1", "0.7", "0.9", "Anything", "A", "Value depends"),
        ("Fat has R.Q. =", "0.7", "0.9", "1", "Anything", "A", "Lower than carbs"),
        ("Protein respiration:", "Uses intermediate products", "Directly", "Not used", "Anything", "A", "Indirect"),
        ("Fermentation yields:", "2 ATP per glucose", "36 ATP", "38 ATP", "Anything", "A", "Much less ATP"),
    ],
    "Plant Growth and Development": [
        ("Plant growth is due to:", "Cell division and expansion", "Only division", "Only expansion", "Anything", "A", "Both"),
        ("Growth regulators are:", "Hormones", "Enzymes", "Nucleic acids", "Anything", "A", "Chemical messengers"),
        ("Auxin promotes:", "Elongation", "Inhibition", "No effect", "Anything", "A", "Cell elongation"),
        ("Gibberellin causes:", "Stem elongation", "Root growth", "Flowering", "Anything", "A", "Stem growth"),
        ("Cytokinin promotes:", "Cell division", "Elongation", "Inhibition", "Anything", "A", "Division"),
        ("Abscisic acid causes:", "Dormancy", "Growth", "Flowering", "Anything", "A", "Dormancy"),
        ("Ethylene causes:", "Fruit ripening", "Leaf fall", "Both", "Anything", "A", "Ripening"),
        ("Photoperiodism is response to:", "Day length", "Temperature", "Water", "Anything", "A", "Light period"),
        ("Vernalization is for:", "Flowering", "Germination", "Growth", "Anything", "A", "Cold requirement"),
        ("Senescence is:", "Aging", "Growth", "Flowering", "Anything", "A", "Degeneration"),
    ],
    "Digestion and Absorption": [
        ("Digestion breaks:", "Complex food to simple", "Simple to complex", "No change", "Anything", "A", "Hydrolysis"),
        ("Salivary amylase digests:", "Starch", "Proteins", "Fats", "Anything", "A", "Starch to maltose"),
        ("Pepsin digests:", "Proteins", "Carbohydrates", "Fats", "Anything", "A", "Proteins in stomach"),
        ("Pancreatic enzymes digest:", "All major nutrients", "One nutrient", "No nutrients", "Anything", "A", "Comprehensive"),
        ("Intestinal enzymes complete:", "Final digestion", "Initial", "No role", "Anything", "A", "Final step"),
        ("Villi increase:", "Surface area", "Volume", "Length", "Anything", "A", "Absorption"),
        ("Absorbed nutrients go via:", "Blood and lymph", "Only blood", "Nothing", "Anything", "A", "Two systems"),
        ("Fatty acids absorbed as:", "Chylomicrons", "Glucose", "Amino acids", "Anything", "A", "Lymph"),
        ("Glucose absorbed by:", "Active transport and facilitated diffusion", "Simple diffusion", "No absorption", "Anything", "A", "Energy requiring"),
        ("Mineral absorption uses:", "Active and passive transport", "One method", "No method", "Anything", "A", "Multiple methods"),
    ],
    "Breathing and Exchange of Gases": [
        ("Respiration provides:", "Oxygen for oxidation", "CO₂ removal", "Both", "Anything", "A", "Dual function"),
        ("Exchange occurs by:", "Diffusion", "Active transport", "Osmosis", "Anything", "A", "Passive movement"),
        ("Respiratory center is in:", "Medulla oblongata", "Cerebrum", "Cerebellum", "Anything", "A", "Brain stem"),
        ("Surfactant reduces:", "Surface tension", "Pressure", "Volume", "Anything", "A", "Respiratory distress"),
        ("Tidal volume is:", "Normal breathing volume", "Max volume", "Residual", "Anything", "A", "Normal"),
        ("Vital capacity is:", "Maximum breathing volume", "Normal", "Residual", "Anything", "A", "Exhaled max"),
        ("Oxygen transport via:", "Hemoglobin", "Plasma", "Dissolved", "Anything", "A", "Red blood cells"),
        ("CO₂ is mainly transported as:", "Bicarbonate ions", "Dissolved", "Carbamino", "Anything", "A", "Dissolved ions"),
        ("Hypoxia is due to:", "Low oxygen", "High CO₂", "Nothing", "Anything", "A", "Oxygen deficiency"),
        ("High altitude causes:", "Hyperventilation", "Hypoventilation", "No change", "Anything", "A", "Low O₂"),
    ],
    "Body Fluids and Circulation": [
        ("Blood consists of:", "Plasma and formed elements", "Water only", "Cells only", "Anything", "A", "Components"),
        ("Plasma proteins include:", "Albumin, globulin, fibrinogen", "Only albumin", "Only globulin", "Anything", "A", "Three types"),
        ("RBCs contain:", "Hemoglobin", "Myoglobin", "Insulin", "Anything", "A", "Oxygen carrier"),
        ("WBCs provide:", "Immunity", "Clotting", "Transport", "Anything", "A", "Defense"),
        ("Platelets essential for:", "Clotting", "Transport", "Immunity", "Anything", "A", "Coagulation"),
        ("Blood group is determined by:", "Antigens on RBC", "Antibodies", "Plasma", "Anything", "A", "Surface markers"),
        ("Rh factor is:", "Another antigen", "Antibody", "Nothing", "Anything", "A", "Additional"),
        ("Cardiac cycle includes:", "Systole and diastole", "One phase only", "No phase", "Anything", "A", "Contraction/relaxation"),
        ("Systole is:", "Contraction phase", "Relaxation", "Both", "Anything", "A", "Pumping"),
        ("Diastole is:", "Relaxation phase", "Contraction", "Both", "Anything", "A", "Filling"),
    ],
    "Excretory Products and Their Elimination": [
        ("Ammonotelism is excretion of:", "Ammonia", "Urea", "Uric acid", "Anything", "A", "Ammonia"),
        ("Kidney consists of:", "Nephrons", "Glomerulus", "Cortex only", "Anything", "A", "Functional units"),
        ("Glomerulus filters blood due to:", "Hydrostatic pressure", "Osmosis", "Diffusion", "Anything", "A", "Pressure"),
        ("Tubular reabsorption is by:", "Active and passive transport", "Only diffusion", "No reabsorption", "Anything", "A", "Selective"),
        ("Antidiuretic hormone affects:", "Collecting duct", "Proximal tubule", "Loop", "Anything", "A", "Water reabsorption"),
        ("Renin is from:", "Juxtaglomerular apparatus", "Collecting duct", "Cortex", "Anything", "A", "Kidney cells"),
        ("Kidney failure requires:", "Dialysis or transplant", "Medication", "No treatment", "Anything", "A", "Artificial kidney"),
        ("Dialysis removes:", "Waste from blood", "Water only", "Nothing", "Anything", "A", "Waste removal"),
        ("Micturition is:", "Urination", "Filtration", "Secretion", "Anything", "A", "Voiding"),
        ("Kidney stones are:", "Calcium deposits", "Protein deposits", "Sugar deposits", "Anything", "A", "Crystalline"),
    ],
    "Locomotion and Movement": [
        ("Human skeleton has:", "Axial and appendicular", "One part", "No division", "Anything", "A", "Two divisions"),
        ("Joints allow:", "Movement", "Growth", "No movement", "Anything", "A", "Motion"),
        ("Synovial joints have:", "Fluid-filled cavity", "No cavity", "Bony contact", "Anything", "A", "Free movement"),
        ("Pivot joint allows:", "Rotational movement", "Flexion only", "Extension only", "Anything", "A", "Rotation"),
        ("Muscles contract due to:", "Sliding filament theory", "Expansion", "No change", "Anything", "A", "Actin-myosin"),
        ("Red fibers have:", "More mitochondria", "Less myoglobin", "No myoglobin", "Anything", "A", "Slow twitch"),
        ("White fibers have:", "Less mitochondria", "More myoglobin", "Both", "Anything", "A", "Fast twitch"),
        ("Tetany is:", "Sustained contraction", "Single contraction", "No contraction", "Anything", "A", "Continuous"),
        ("Muscle fatigue due to:", "Lactic acid", "Glucose", "ATP surplus", "Anything", "A", "Acid buildup"),
        ("Arthritis is:", "Joint inflammation", "Bone formation", "Muscle tear", "Anything", "A", "Joint problem"),
    ],
    "Neural Control and Coordination": [
        ("Neurons are:", "Functional nerve cells", "Supporting cells", "Muscle cells", "Anything", "A", "Nerve units"),
        ("Nerve impulse is:", "Electrochemical", "Only electrical", "Only chemical", "Anything", "A", "Combined"),
        ("Synapse is:", "Junction between neurons", "Nerve ending", "No junction", "Anything", "A", "Signal transfer point"),
        ("Neurotransmitters are:", "Chemicals for transmission", "Enzymes", "Hormones", "Anything", "A", "Messengers"),
        ("CNS includes:", "Brain and spinal cord", "Peripheral nerves", "Autonomic", "Anything", "A", "Central"),
        ("PNS includes:", "All nerves outside CNS", "Spinal cord only", "Brain only", "Anything", "A", "Peripheral"),
        ("Reflex arc is:", "Automatic response path", "Voluntary pathway", "No path", "Anything", "A", "Quick response"),
        ("Autonomic nervous controls:", "Involuntary functions", "Voluntary", "Skeletal muscles", "Anything", "A", "Unconscious"),
        ("Sympathetic division is for:", "Fight or flight", "Rest and digest", "Growth", "Anything", "A", "Emergency"),
        ("Parasympathetic is for:", "Rest and digest", "Fight or flight", "Activity", "Anything", "A", "Normal"),
    ],
    "Chemical Coordination and Integration": [
        ("Hormones are:", "Chemical messengers", "Enzymes", "Nutrients", "Anything", "A", "Signaling molecules"),
        ("Endocrine glands secrete:", "Into bloodstream", "Ducts", "Tissues", "Anything", "A", "Blood transport"),
        ("Insulin is from:", "Beta cells", "Alpha cells", "Liver", "Anything", "A", "Pancreas"),
        ("Glucagon is from:", "Alpha cells", "Beta cells", "Delta", "Anything", "A", "Opposite of insulin"),
        ("Thyroid hormones include:", "T₃ and T₄", "Only T₃", "Only T₄", "Anything", "A", "Two hormones"),
        ("Calcitonin reduces:", "Blood calcium", "Blood glucose", "Thyroxine", "Anything", "A", "Lower Ca²⁺"),
        ("Adrenaline is from:", "Medulla", "Cortex", "Liver", "Anything", "A", "Adrenal"),
        ("Cortisol is from:", "Cortex", "Medulla", "Pancreas", "Anything", "A", "Adrenal"),
        ("Growth hormone from:", "Anterior pituitary", "Posterior", "Hypothalamus", "Anything", "A", "Pituitary"),
        ("Feedback regulation is:", "In endocrine system", "One-way", "No regulation", "Anything", "A", "Self-regulation"),
    ],
    "The Fun They Had": [
        ("This story is about:", "Future education", "Past education", "Current", "Nothing", "A", "Future schooling"),
        ("Technology in future allows:", "Online classes", "No classes", "Only textbooks", "Anything", "A", "Digital learning"),
        ("Story comparing:", "Traditional vs modern", "All modern", "All traditional", "Anything", "A", "Both methods"),
        ("We should value:", "All forms of learning", "Only one", "Ignore", "Anything", "A", "Learning is key"),
        ("This chapter is from:", "English", "Hindi", "Maths", "Science", "A", "English reading"),
    ],
}


def generate_chapter_mcq(chapter_name):
    if chapter_name in chapter_questions:
        return chapter_questions[chapter_name][:10]
    
    lower_name = chapter_name.lower()
    
    topics = {
        "Maths": [
            (f"Key concept in {chapter_name}:", "Problem solving", "Memorizing formulas", "Ignoring", "Skipping", "A", f"Solve {chapter_name}"),
            (f"{chapter_name} involves:", "Complex calculations", "Simple numbers", "Stories", "Nothing", "A", f"Math concepts"),
            (f"Practice {chapter_name}:", "Solving examples", "Reading only", "Memorizing", "Ignoring", "A", f"Practice makes perfect"),
            (f"{chapter_name} helps in:", "Higher mathematics", "Nothing", "Everyday math", "Nothing", "A", f"Foundation"),
            (f"{chapter_name} uses:", "Multiple formulas", "One formula", "No formulas", "Nothing", "A", f"Formulas application"),
            (f"This is part of:", "Mathematics", "Science", "Commerce", "Arts", "A", "Core subject"),
            (f"Key topic in {chapter_name}:", "Calculations", "Theory", "Nothing", "One type", "A", f"Complex topic"),
            (f"Understanding {chapter_name} needs:", "Practice", "Memory work", "Ignore", "Nothing", "A", f"Application"),
            (f"To master {chapter_name}:", "Solve problems", "Read theories", "Memorize", "Nothing", "A", f"Problem solving"),
            (f"In exam, {chapter_name} carries:", "Significant weight", "Less weight", "No weight", "Nothing", "A", f"Important"),
        ],
        "Science": [
            (f"What does {chapter_name} teach:", "Scientific principles", "Nothing", "History", "Math", "A", f"Concept clarity"),
            (f"This chapter covers:", "Core science topics", "Simple topics", "No topics", "Anything", "A", f"Important topics"),
            (f"We should understand:", "Fundamental laws", "Just definitions", "Nothing", "One concept", "A", f"Laws"),
            (f"Science in {chapter_name}:", "Theories and applications", "Only theories", "Only practicals", "Anything", "A", f"Theory + Practice"),
            (f"From this we learn:", "Natural phenomena", "Just facts", "Nothing", "No relevance", "A", f"Nature"),
            (f"This chapter is:", "Important for understanding", "Optional", "Not necessary", "Anything", "A", f"Required"),
            (f"Practical applications:", "Are numerous", "Few", "None", "Nothing", "A", f"Uses"),
            (f"Our duty:", "Apply knowledge", "Ignore", "Waste", "Nothing", "A", f"Learn and apply"),
            (f"Remember key concepts:", "For life", "For exam only", "Nothing", "No use", "A", f"Permanent learning"),
            (f"This is from:", "Science subject", "English", "Maths", "History", "A", "Core science"),
        ],
        "English": [
            (f"Reading {chapter_name}:", "Comprehension important", "Vocabulary only", "Grammar", "Nothing", "A", f"Read carefully"),
            (f"Lesson from {chapter_name}:", "Life values", "Words", "Fun", "Nothing", "A", f"Values matter"),
            (f"Characters teach:", "Important lessons", "Nothing", "Only stories", "Anything", "A", f"Life skills"),
            (f"This story illustrates:", "Human values", "Facts only", "Nothing", "No theme", "A", f"Theme"),
            (f"From this we learn:", "Multiple interpretations", "One meaning", "Nothing", "No learning", "A", f"Learning"),
            (f"The writing style:", "Descriptive and vivid", "Simple", "No description", "Anything", "A", f"Style"),
            (f"Vocabulary is:", "Rich and varied", "Limited", "Simple", "Anything", "A", f"Vocabulary"),
            (f"Grammar usage:", "Important", "Not needed", "Optional", "Nothing", "A", f"Need for exams"),
            (f"Chapter type:", "Prose or poem", "Essay", "Article", "Nothing", "A", f"Reading passage"),
            (f"This from:", "English textbook", "Hindi", "Maths", "Science", "A", "English subject"),
        ],
        "Hindi": [
            (f"कहानी {chapter_name}:", "कहानी है", "कुछ नहीं", "कुछ भी", "कोई नहीं", "A", f"{chapter_name} = story"),
            (f"{chapter_name} से सीखें:", "सीख", "भूलें", "नकारें", "उपेक्षा", "A", f"सीख {chapter_name} से"),
            (f"इस अध्याय में:", "कहानी और कविता", "व्याकरण", "शब्दावली", "कुछ भी", "A", f"Learning in {chapter_name}"),
            (f"पाठ {chapter_name} का:", "महत्व", "कोई नहीं", "कम", "अधिक", "A", f"Value of {chapter_name}"),
            (f"हमें {chapter_name} से:", "सीखना चाहिए", "भूलना चाहिए", "नकारना चाहिए", "छोड़ना चाहिए", "A", f"Learn from {chapter_name}"),
            (f"कविता में:", "रचनात्मकता", "व्याकरण", "शब्द", "कुछ भी", "A", f"Poetry"),
            (f"निबंध में:", "लेखन कौशल", "कहानी", "पत्र", "कुछ भी", "A", f"Writing skills"),
            (f"व्याकरण:", "महत्वपूर्ण", "जरूरी नहीं", "सीखना", "नहीं सीखना", "A", f"Grammar"),
            (f"यह है:", "हिंदी पाठ", "अंग्रेज़ी", "गणित", "विज्ञान", "A", f"Hindi chapter"),
            (f"पाठ से:", "बहुत कुछ सीखते हैं", "कुछ नहीं", "कम", "कुछ", "A", f"Learning"),
        ],
        "Social Science": [
            (f"What does {chapter_name} teach:", "History and geography", "Nothing", "Science", "Math", "A", f"Social topics"),
            (f"This chapter deals with:", "Social aspects", "Science", "Sports", "Entertainment", "A", f"Social topics"),
            (f"We should understand:", "Past events", "Ignore", "Memorize", "Nothing", "A", f"Past matters"),
            (f"Chapter content:", "Critical for exams", "Optional", "Not important", "Anything", "A", f"Important"),
            (f"Our duty:", "Learn from past", "Ignore", "Waste", "Nothing", "A", f"Learn"),
            (f"Important events:", "Should be studied", "Not studied", "Ignored", "Nothing", "A", f"Key events"),
            (f"From this we learn:", "Lessons from history", "Nothing", "Just dates", "Entertainment", "A", f"History lessons"),
            (f"This is from:", "Social Science", "English", "Maths", "Science", "A", "Social subject"),
            (f"Maps and timelines:", "Are important", "No need", "Optional", "Nothing", "A", f"Tools"),
            (f"Subject includes:", "History, geography, civics", "Only one", "Nothing", "Anything", "A", f"Multiple areas"),
        ],
    }
    
    for subject_key, qs in topics.items():
        if subject_key.lower() in lower_name:
            return qs
    
    return topics["Science"][:10]


total = 0
for chapter in chapters:
    chapter_name = chapter.name.strip()
    subject = chapter.subject.name
    
    MCQQuestion.objects.filter(chapter=chapter).delete()
    
    qs = generate_chapter_mcq(chapter_name)
    
    for order, q in enumerate(qs):
        MCQQuestion.objects.create(
            chapter=chapter,
            question_text=q[0],
            option_a=q[1],
            option_b=q[2],
            option_c=q[3],
            option_d=q[4],
            correct_option=q[5],
            explanation=q[6],
            order=order
        )
        total += 1
    
    print(f"[{total//10}] {subject} - {chapter_name[:35]}: {len(qs)} MCQs")

print(f"\n{'='*60}")
print(f"Done! Generated {total} unique MCQs for Class 11")
print("="*60)